#+title: 记录一次失败的创业经历
#+date: Wed Sep  9 13:00:17 2026
#+author: Zi Liang
#+email: zi1415926.liang@connect.polyu.hk
#+latex_class: elegantpaper
#+filetags: ::


我之前认为只有庸俗的东西才会遵循周期规律而发起而消失。比如校园恋爱——入学渐渐开始谈，毕业结束等等。我从来没想到我的第一次创业的失败经历竟然也如此庸俗。本文旨在记录这次创业的全过程并提供我的思考。
* 总览

开始时间应该是2024年秋天。当时的idea是：基于LLM的agent越来越重要，由此衍生的System Prompt的设计将变得越来越重要，因为基于的应用其本质便是一个LLM外加一个复杂的instruction与其他东西的套壳。于是，当时衍生出了一个想法：可否做一个meta-agent：即面向于提升agent应用开发水平和效率的AI Agent呢？换句话说，能否提供一个服务，使得用户可以在这个服务之下被引导更好地理解自我的agent产品开发需求，同时在毫无prompt engineering的背景的前提下仍然能够通过该产品获得自动化的系统prompt提升效果。换而言之，这是一个to B的产品（或者说to 开发者的产品）：就像过去的CS时代程序员需要IDE或者editor一样，认为agent时代的开发者需要我们的产品。

为了这个目的，我同我的一个朋友开始了探索。2024年，vibe coding甚至都还完全不成熟，那时候最火的还是cursor. 对前后端开发几乎一窍不通的我们开始了测验。我们花了大概几个月的时间构建出了一个完善可用并且我觉得效果还算可以的网页应用，我们称之为prompt designer. 我们还截取了一堆动图来表明designer包含哪些功能，定价每个月7美刀。

然后在2025年9月，我们开始尝试在小红书上宣传。

然后在2026年8月，Prompt Designer彻底关停。


我们的开发数据：
1. 即使到最后，我们也没弄出来中文付费渠道。
2. 我们曾经有一个基于信用卡的付费渠道，但是我忘记它是否可用了。
3. 我们有用户（被小红书的帖子吸引来的），他们使用qq邮箱等各种邮箱注册了，但是无一例外没有付费。
4. 这个项目在关停之前的漫长的许多个月份里，我们没有进行过哪怕一次更新。 ---> 所以朋友是对的，必须关掉了。

* 思考

我觉得这个创业项目失败的原因如下：

+ 没有时间。 这个是朋友认为的问题。即我们两个researcher都无法为这个项目倾注我们所有的时间，因为我们各自都有各自的科研要忙。尤其是我，我是一个很喜欢emit的人，无法过于倾注在提升prompt designer上。
+ 想法过于fancy（高情商）或者说想法几乎无用。事实证明prompt的engineering核心不在于lexical level的斟酌，而在于背后的思维。发展到今天，一方面，如何构造一个loop，如何协同工具，如何管理上下文，这些high level的思维层面的东西其实是最重要的，而system prompt的撰写本身，并没有那么重要。另一方面，不得不说现在的LLM对prompt的适应性，在经历了长期的post-training之后，已然变得很强，由此不再需要过多的特殊处理。
+ 我们在开发之外推进的太少了。我认为这才是核心原因。
  + 我们没有拿到哪怕一笔的funding. 【感觉就很奇怪，因为我甚至连email都没收到】
  + 事实上我也仅仅申请了一次funding. 我觉得这是不合理的。
  + 我们并没有怎么宣传。只发了一次小红书。No twitter, No reddit, No website level, None of others.
  + 作为一个产品，我们甚至没有合理的付费渠道。
    + 作为一个没有信用卡的中文用户，它即使想花钱也做不到。没有微信支付，支付宝支付这些。
    + 英文用户甚至不知道，因为我们没有宣传。
    + google搜我们不在第一页，也不在第二页。。


* 我的教训


我认为这次创业对我的影响最大的地方是，让我意识到Afford by Myself的重要性。Musk说过如果一个人面对一个没有搞懂的东西试图走捷径绕过去那么这个没有被搞懂的东西还会继续出现。我觉得这个观点是正确的。 *我对于这次创业的失落感其实是我认为这条探索的trace所带来的结果并没有被很好地累积下来作为我的原始积累。* 尽管这次创业失败了，但是其实跑通了非常多的东西：
1. 有了Domain name+Cloud Server+Backend+Frontend+Strip付费的全流程。这其实对于一个独立的产品网站来说完全够用了。按照常理，以后的创业产品在这些工程角度上就不再需要耗费精力了。
2. 尽管我们没有主动发邮件找客户，尽管我们没有很多宣传，但是至少尝试了最基本的宣传。
3. ......


可是现在服务器关停了。Moreover AI也如同历史的尘埃的一样消失了。



* 结束语

我常常有一种感觉，刚受伤时人总是不知道痛的，只是不理解。不理解好端端的为什么突然出现一道伤口。那天晚上朋友发消息来说服务器关停，心里觉得情理之中，因为早就有这种感觉了。——他早已毕业。而我也将要毕业。这时候提出确实也是再合适不过的事情了。或许那些毕业就分手的校园恋情也是这样。不是因为毕业干扰了爱情由此充当了什么对抗噪声，而是这份曾经充盈的爱情早已萎缩掉了，其中早已不包含任何希冀、期待、好奇、以及无关紧要的理想。因为这些内在的东西垮掉了，所以爱情早已死掉了。恰逢毕业，适合体面地提出罢了。

