#+title: How to Improve the Impact of My Research
#+date: Mon Apr  7 16:40:00 2025
#+author: Zi Liang
#+email: zi1415926.liang@connect.polyu.hk
#+latex_class: elegantpaper
#+filetags: :research:



Recently I am thinking about a critic question of "how to improve the impact of my publicated papers". This concern raised because the following observations:
+ The Paper-Researcher relationship changes. In past, it is many researchers talking about a few publicated studies. but currently, there emerged more and more "top-tier" papers, where even a person under a narrow research domain cannot read out the publicated studies in his/her field easily. Therefore, publication is not the endpoint of "acceptance", "MAKE OTHER PEOPLE KNOW MY WORK" is the endpoint of such an "acceptance".
+ The paper becomes a thing "almost everyone owns". In the past ages, people with three studies can be seen as a mature researcher in corresponding field. However, currently, many people own a lot of paper, and even get acceptance of a lot of their works every year. Under such a situation, I suffer from the choice: either obtain many publications, or have some famous publications, or the both.

Specifically, under such a "red sea" situation, I must consider: does there exist any other subjective and objective metric that distinguish a researcher with others?

I think the answer is yes. Citations, can be seen as a simple but effective metric for that. Besides, let all people in this field know me, is also an important solution.

Therefore, I propose a new plan to improve the impact of my research, named "Plan Poisoning". I will regard my publications and my precious works as the poisoning data, and aim to inject them into the Internet by myself.

The detailed plan is as follows:

1. Join academic conference more frequently. This provides me the opportunity to connect with other person in this field. To do that, I need to submit my paper with a certain frequency.
2. Once a study is accomplished, I need to announce and introduce it under the following platforms:
   1. Wechat
   2. X
   3. Discord
   4. Zhihu
   5. RedNote
   6. Blog in this website
   7. I require myself to write email to share my study with other people
   8. Write Chinese article to some Wechat platforms
   9. Make video and submit it into Youtube and Bilibili
3. Seeking for collaborators to improve the publications of non-first-author publications.

Let me see the effectiveness of this strategy on <2025-09-01 Mon>.

