#+title: 对2025年的自我反思以及最后一个月的生存计划 
#+author: 梁子
#+date: Tue Dec  9 09:48:50 2025
#+email: 2273067585@qq.com 
#+latex_class: elegantpaper


* Preliminary

** 实验性质的人生目标
 成为中文语境传统下的“好”。即梦想成为，在儒家意义下的君子与圣人，达到修齐治平的统一和为此所需要的一切道德上的以及美学上的需求，立功立言立德；无限趋近于道，晓知天，保持纯洁纯一的赤子之心；解除自我的烦恼，具备传道人的特质，面对任何事情都不能失神或无主，即使是死亡。

 在上述自我的建立上，成为一个把一生献给人类的人。


 将上述目标按照现象学理论进行拆解：
 
** 对人生的现象学分析与庸俗性表达

按照现象学理论，将对自我人生状态的观测拆为若干维度：
+ 我的内心是否平静？
+ 我的生活是否是有计划性的、受到自我意识控制的？
+ 我是否离“道”越来越近？
+ 我是否能够充分感觉到自我的进步？
+ 我的身体是否越来越好？
+ 我有没有照顾到自我的情绪？

如是，从世俗生活的角度进行进一步拆解：

+ 身体素质
  + 睡眠状况
  + 跑步量
  + 武侠量
  + 比赛量
  + 健身量
+ 心境
  + 止量
  + 观量
+ 工作
  + 代码提交量
  + 科研时间
+ 情绪
  + 面对面的交谈量
  + 线上交谈量
  + 新的人认识量
  + 旧的人认识量
+ 成长性
  + 对无意识行为的杜绝程度（即推荐系统的排斥程度）
  + 计划性
  + 维护自我成长性体系


后续内容便是基于以上维度进行评判。

* 宏观上的反思

+ 在过去一年，我很显然没有思考清楚人生意义的问题。很明显我在思维上已经否定了享乐主义，并且认为我的人生意义是建构出诸如“沙滩上的城堡”这种具有美学上的比喻的东西，但是这个东西是严重脱节的。——即这个比喻承认了自我所做行为的悲壮以及承认了每个人的意义的不同，但是这个比喻 =严重脱节于= 我的现实世界的行为，使得我与现实世界里的一切行为产生了脱节。这是一个大而空的东西。
+ 在过去一年，我对于人生的自我规划是完全失灵的。我只是在大脑里隐隐有一个人生规划，类似于“过去一年我要做三篇论文”这种。这导致我整个的一年可以说是毫无建树，除了科研。我急需一套新的方法来重新掌控自己颓废而堕落的一年。
+ 在过去一年，我沉迷于推荐系统和手机。——这是由于我的无目标性造成的。
+ 在过去一年，每次面对巨大的困难，我都会退缩，然后浪费掉大量的时间。——这是由于我脆弱的主体性和在方法论上的巨大缺陷造成的。


* 具体的思考

+ 身体素质
  + 睡眠：我应该严格执行10:45睡眠制度，并以切香肠的方式提前。这个时间为红线。
  + 跑步：我抛弃了去年培养的跑步习惯，这是巨大的错误。我应该立刻重新捡起这个习惯。
  + 武侠：我应该立刻捡起这个习惯。
  + 比赛：还可以。因为总有人可以约，所以我一直在被动参加。
  + 健身：我不应该对健身表达任何生理上的厌恶。我厌恶的只是健身背后所代表的那种功利性的态度和一个人卖弄自己身体的恶心感觉，但是我不应该否认肌肉训练、耐力训练等训练的积极意义。同样地，我自己本身也常常在这些训练当中受益，所以我更不应该否认他们。我应该重拾他们。
+ 心境
  + 止：我学会了安那般那。但是需要提高。
  + 观：毫无进展。
+ 工作
  + 代码提交量：自从8月份后，出现了巨大的下滑。
  + 科研时间：自从八月份后，出现了巨大的下滑。我应该重新约束自己的科研时间，保证6个小时每天的基础科研时间，并列为红线。
+ 情绪
  + 我不应该让自己有太多的情绪波动。
  + 我应该永远真诚微笑地对待他人，包容他人，无论他们对我做了什么。当然，我不能放弃我的直率的一面，但是要怀有礼貌。
  + 新人：我应当移除自我的社恐特性。社恐不符合周礼对君子的要求。我应当成为一个游刃有余地进行社交的人，不应该在线上或线下的交流中呈现出任何的对沟通渠道的偏好。我应当对男生和女生保持同样的热情，不应当对女人由于生理特性的特点表达出任何偏好，或者对男人由于相同点过多而表达出任何偏好。我应当足够谦虚、足够自信、同时在举止之间表达出符合君子行为的一切。
  + 旧人：永远维护旧人之间的感情。永远谦虚、尊重他们。要善于倾听理解他们的情绪，倾尽自己的能力解决他们的困难，与他们站在一起。如若需要给他们倾诉，要合理考虑倾诉的量，同时不要给他们造成太多麻烦。要记得赞美和保持礼貌。
+ 成长性
  + 无意识行为：在禁欲、禁APP等行为上进行系统性的监测。
  + 计划性：事实证明，现有的emacs org mode的使用并不有效。我应该使用基于时间的TODO计划当中。事实证明，没有计划的话，无意识的时间消耗很容易产生，生活的掌控感也会被无限制削弱。



* 未来的计划

1. 从现在开始，撰写今日计划、明日计划、昨日反思。如此循环下去。
2. 从现在开始，约健身房，恢复跑步。
3. 今晚10:45睡觉。
