#+title: 对过程导向与结果导向的重新思考
#+date: Sun Dec  8 15:24:27 2024
#+author: Zi Liang
#+email: zi1415926.liang@connect.polyu.hk
#+latex_class: elegantpaper
#+filetags: ::


我一直都标榜自己是一个只关注过程但是不重视结果的人。但是很显然我不是。我渴望未曾到来的成功，我害怕遥远处所蛰伏的失败的可能性。我信任玄学——即使是荒谬的、发生在过往成功之前的事情，比如看的文字，吃的餐饭，甚至是出结果当日期，都被我当做是滋生出成功的因素。以上事情都让我重新反思结果导向的决策与过程导向的决策两类。

* 反馈的意义

控制理论中，一个动力学系统可以通过观测某变量的实际值与期待值的差距来对自身进行调整，从而在理论上令该系统的误差收敛。在强化学习中，Agent通过与环境交互来决策如何行动，并根据环境所传来的奖励更新自我对环境的理解（hidden state的构建过程）与决策（action的构建模型）。类似思想或许在其他领域也出现。

反馈是上述两类系统的基础。其基本假设是：1）所有的操作作用于物理世界之后都会变形。所以需要一个类似于镜子的东西来让模型进行调整；2）世界（world）早已复杂到了无法通过规则或者某些固定范式来制定的程度。所以只能通过反馈反复试错不断摸索。比如围棋，下在四周的四个大点已成范式，但是这未必是围棋游戏下的最优。各种前人总结的“局部小点最优”在游戏版本反复迭代下或许不再是最优的版本答案。

以上两点够成了获取反馈和处理反馈的强烈需求。

* 结果导向

结果导向是建构在反馈基础上的行动方法。

具体说就是：由于对环境理解的困难，所以常常无法对一个人当行为进行任何先验的价值判断。一个人的价值应当是取决于并完全取决于他所带来（导致）的反馈（结果）。比如不同地区的两棵枣树，一棵所结果实大而甜，一棵小而苦。从期待吃到好果子这一目标看，前者完胜。任何其他的描述以及客观差异其实可以被忽略。同理，一对邻居家年龄相仿的两个男童自出生三十年后的评价，同样可以通过他们的收入进行结果导向的评判。二人之家境、中学同桌、学习情况、所选专业、后面工作当城市、工作行业、选的对象等等各种区别在上述情况中都可以隐去。三十年后，男子乙看到男子甲的成就，于是根据男子甲的成就调整自己，或者调整自己的孩子当一生。——这可以认为是一种结果导向的决策。身边小事莫不如是。

从上述分析中可知：结果导向是一种最自然、最朴素、最合理、最直接的导向。

结果。“结果”——不会随着人的主观意愿转移，只会随着这个世界和社会的复杂流转而在某个时刻呈现出某一面。这使得从结果出发是唯一理性、客观的与世界打交道的方法。因此，对于怀有固定目的性的决策而言，结果导向几乎一定是必然的出路。考虑一个复杂的群体（比如菌），这个群体的目标的目标是一年时间让群体的总重量提升到10千克。那么身为菌的决策者，其实最好的行为就是每个月（或每周）查看重量的提升率，根据提升情况对部分菌的行为做成调整。现在考虑一个菌的国，这个国一共包含了诸多菌群。每个菌群都获得了他们所需要完成的指标——不管怎么去做。于是王国就可以通过结果导向运转起来了。

上一段论述了结果导向的合理性，从中可以发现结果导向所需要的一些要素：1）必须要有一个明确的可量化的目标。比如一个博士生，当他说出一句“三年发出三篇顶会以求毕业”时，他才具有了采用结果导向的能力。2）必须要有一个明显构成反馈的方法。比如该博士生每中一篇，就是强正反馈，等等。3）必须要充分考虑足够多的“其他维度”，确保优化过程不是在非条件优化中进行的。比如该学生至少不能造假，不能过分透支身体，等等等等。
4）必须结束。比如该学生口中的“三年”，或者“博士生涯”。等到该目标达成了，方是思考下一步的时间。

根据以上观点，其实可以构建出一个大多数人不会承认但是基本属实的、符合现代社会道德的“人生意义版本”：

定理1 「人生意义的结果导向」。当今社会，人生的意义和目标在于尽可能早地赚到足够多的钱。同时需要添加以下限制条件：1）不能过度透支身体；2）不能违法；3）不能卖国；4）不能严重违反社会道德舆论；5）不能损害自我尊严；……

证明如下：首先可以证明我们所处的社会是一个社会高度分工化、市场经济高度发达的社会。根据资本主义的基本原理，可以认为一切商品的交换价值都可以被金钱来衡量，而身处于社会当中的我们的价值又进一步可以被曾经所创造的所有商品的使用价值、所拥有的金钱量、以及生产商品时的使用价值效率三者衡量。社会的总体目标是使得当前所有商品的交换价值之和以及增量最大化，因为每个个体的目标在于尽可能早的赚到尽可能多的钱。不设置上限。

定理1中列举了5条限制。按照强化学习理论，这五条都可以酌情去除。这是为什么？这是因为我们预设了决策模型的黑盒属性。伤害身体对于社会是好事还是坏事？对于个体是好事还是坏事？这并不好说。“法”、“道德”、“尊严”等名词都是人类所发明，类似于围棋里的各种trick，类似于游戏里“剑圣先出电刀”等众人积累出来的范式，未必正确，也未必符合当前版本。因此，假如你身为老板兢兢业业遵纪守法，然后你的竞争对手偷蒙拐骗五年，最后积累了强大的资本，垄断行业，最后收购了你的公司。站在会议室的你首先想道：这人不守规矩，违法乱纪，劣币驱逐我这个良币，呜呼哀哉。 然后你又想道：我觉得他不守法，但是或许他心里想的是，老子甘愿冒着蹲监狱的风险扩张，我行业做的这么大实属应该。即使老子没成，也认了。 这时你听到你的竞争对手在给你解释：我虽然有些无耻，但是我是为了让我们的行业早日统一，降低成本大力研发，以共同应对来自海外强势对手的威胁。我实在是为了整个行业和民族在考虑。 客观地说，你觉得他说的好像也不错。真真假假，你能理解吗？


以上就是我对结果导向的全部理解。上段的例子是在说：“结果导向”是 *不可解读* 的。当一个人选择了结果说话，就不应该有解释，也不应该谈论意义。 /结果在，就没有意义。结果本身就是意义。/

由此可以理解很多流行语：（1）笑贫不笑娼。 娼是一种评判，一种不适用于市场经济的评判。计划经济里只有月薪3000的人、月薪10000的人、月薪100000的人，没有君子、娼妓、贵族、绅士、主人、奴隶等东西。高收入人群可以拿到过往时代的一切好的头衔，同时可以恣意“扮演”一切不好的角色。由于道德是建构在社会生产之上的文化，所以道德往往会过时。娼的指控被大家漠视，不是大家笨蛋，而是发明这句话酸来酸去的人笨蛋。与娼相比，贫是结果导向的社会下的原罪。因为贫代表不拥有也无法高效率生产具有交换价值的商品。 （2）自有大儒为我辩经。 这背后的逻辑是，在结果导向的思考方式下，意义与解读在结果面前毫无意义。打比赛，赢是一切；写论文，中是一切；工作，赚钱是一切。当一个人成为首富，过往的一切都会具有合理性；当一个民族屹立，同样如是。

* 结果导向的困难

如前所述，结果导向是一种最本原的探索与理解世界的方式，且不可替代。

这就导致了定理1所述的情形是绝对的真理。不管一个人多么自我标榜，如果他贫穷，实事求是地讲，我想他在一个富豪面前仍然会下意识地自卑。财富、以及财富相关的符号（比如豪车），会在人类生活的方方面面三百六十度无死角地展现出来，教育处在这个社会当中的每一个人。

反对定理1，反对“当今社会，人生的意义和目标在于尽可能早地赚到足够多的钱。”这句话的人，往后余生大概率都会过得很苦。

但是，我一直在怀疑结果导向是否能够用于进行自我管理以及系统治理。
同时我强烈反对结果导向。
我挣扎于：如何在启动过程导向之后摆脱结果导向所带来的影响？

我反对结果导向的原因是：我不能接受看结果而不是看意义这个事情。推导如下：假设人皆有一死。那么人的结果是死——不需要去追求的死。人的生物性由此便会剥夺人的社会性，从而导致人的虚无。

例如，一个人会反驳：我赚那么多钱是为了后面享受生活（所谓的fire），是为了从可乐自由到咖啡自由到龙井自由，从开10万的车到开百万的，是为了数不尽的女孩都喜欢我，是为了体验成千上万人认识我尊敬我的感觉，是为了……

以上所说都对。但是总结起来无非是“放纵欲望，享受生活”。可是正如我们从小到大的假期所经历的那样——当假期快要结束的时候，当周末快要结束的时候，我们是经历了一个从虚无到释然的状态。这或许也是我们面对死亡的状态。

结果导向最大的问题是，只看得到结果。这使得人同机器无分别，使得我虽生已死。






























