#+title: 近期的人生思考与DeepSeek融资的谈话
#+date: Sun Jul 26 12:42:25 2026
#+author: Zi Liang
#+email: zi1415926.liang@connect.polyu.hk
#+latex_class: elegantpaper
#+filetags: ::




* 论“愿景”

一个组织的产生，一个组织本身的维护，一个组织的行为本质上来自于这个组织的愿景。即这个组织的目标是什么，究竟想做成什么事情。

这里面的核心在于本与末的对比。即“想要做成什么事情”这个是本，“做成这个事情产生的收益”是末。

换而言之，名誉、地位、金钱、盈利、社会风评等等都应该被忽视。越是重视这些东西，越无法得到这些东西。应该去除所有对枝叶的追求和向往，专心沉浸在对事物本身的钻研上。这就是成功。

对于科研而言，我对于自己所产生的论文无法被别人看到的焦虑——尤其在当前巨大批量的AI浪潮下，是真实的。然而，我对于科研的浮躁，我对于科研的判断与行动的目标错误同样也是真实存在的。从之前所讨论的无我的角度来看，我应该思考：如果我今日的行为的结果将会被他人完全继承，我会觉得快乐么？我会觉得不甘心乃至于愤怒么？一旦我执着的是“我做出了什么什么”，或者“这个组织做出了什么什么”，这时就代表我仍然是以一种贪恋者的眼光、一种功利性的视角在进行生命活动，此时的我便总会被各种其他的要素干扰，因此永无法做出真正有意义的科研或者产品。

正如牛顿的意思，research的最好境界应当是忘我的。其实一个人处在社会中的各种行为的最好境界都应该是忘我的。做一件事本身最需要的应当是沉浸。而不是想做这个事能够为我带来什么等等等等。这个观点我其实之前已经悟到，但是时时刻刻忘记。这里面涉及到主客体的消解与统一，当时总结出来的思路是：当我在思量“我”时，我已经预设了一个世界。我最然把“我”作为主语，但是实际上此处的我是一个客体，是一个镜子中被凝视的我自己。而当我忘记我时，我的眼中没有了我，只有这个世界。我凝视的、卷动的是这个世界，一点没有我的痕迹，我反而成为了绝对的主体。换句话说，当我不再顾及我，不再谈论我，我反而拥有了我。当我一味强调我，一味思考我，我反而被自我囚禁。 组织体亦复如是。

我不应该思考做一件事情的难度，反而应该沉浸在做这件事的每一个细节里。如此方是对此刻的人生的最好的尊重。

把此刻的生命通过一种名为工作的庸俗的异化方式支付出去，无异于一种对自我的器物化。这似乎在表明我的这两个小时、半个小时、每分钟都对应着这个社会里的几百元、几千元、万元的价值，但是现实是人生的宝贵无法被这些东西所衡量。自我的时间——时刻消散的生命也不应当被这些枝节所束缚。

本与末的倒置所产生的颠倒，是人类社会固有的枷锁，是海德格尔对存在问题思考时产生的批判，也是人最大的“颠倒梦想”。


* 论“克制”

#+begin_quote
你越克制,你越有可能能够做成这层事。这是一个商业上的考
量,当然这是一个宏观的考虑。我觉得这是符合直觉的,至少是符
合我的直觉,或者说至少我是真的这么想的。

我们并没有非常多的其他优势,我们没有什么本事,我们并没
有比别人有钱,也没有说我们人员比其他公司更好,其实没有的。
你想,我们两年前成立这个公司的时候,我们又没有很多钱,又没有
很多卡,又没有什么知名度,又没有什么号召力,我们就是一群非常
平凡的人。

我真的就是一群平凡的人。如果说喜欢的一个叙事是一群平
凡的人做出了不平凡的事情,而不是一群天才做出了不平凡的事情,
这个跟我们的克制是很有关系的,跟我们的克制、跟我们的愿景是
一脉相承的。那么,开源跟商业化会不会有冲突?我觉得在AI这个
事情上面,你不克制,你就不起。
#+end_quote

克制本质上应该是指对主干（愿景）之外的其他事物（金钱、地位、风评）进行的不由自主的过度优化倾向的一种剪枝。


做正确的事情。做自己想做的事情。放下对其他事物的痴迷。不在乎他们。 这就是克制。


#+begin_quote
AI这个事情太大了,利益太大了。我们非常克制,只要能够做
成,最后利益都会非常大。你随便分一点,利益就非常大,所以现在
根本不用考虑拿这里面的哪一部分利益、怎么拿,我觉得根本不用
考虑这件事情,因为这个利益足够大了。
#+end_quote

其实不止是AI, 所有的领域都是这样。把一个东西完成、做好、或者去探索这个行动本身，比思考这个东西的意义、衍生，要重要得多。


* 芝麻西瓜论



#+begin_quote
我觉得这个在商业上是行得通的,是有可能的。如果去年时候
我们用了大笔钱,就跟字节去抢用户,也是一种打法。但是我们选
择是一种非常克制的做法,就是我不跟你去争这个东西,因为后面
还有西瓜,前面的可能都是芝麻。

我不应该什么芝麻都抢了。当然,可能这个芝麻比较大,但我
觉得后面的AI可能前面都不算大。现在来看,去年我们没有在C端
去发力,可能是对的。

因为能看到后面真的是有更大的西瓜,前面真的只是一些小芝
麻。如果去年我就有很多钱,然后把这个事情做得非常大的话,有
什么好处?你并没有得到什么东西。这些是我的真实想法,因为我
觉得后面的AGI机会应该是非常大的,后面的AGI机会永远是非常
大的。
#+end_quote

这是典型的对一个技术处于上行期时（比如对AGI的幻视）所产生的论点。

但是我还是愿意同意。因为我也是想着继续走下去。

事实证明，没有冲击C端是对的，AI产品在C端的黏度并没有那么高。

* 阶梯论与持续学习


#+begin_quote
因为我们发现,通过思维链的方式,可以让智能达到一个更高
的水平。通过它自己思考,可以让这个上限,可以让这个AI能做更
多的事情。那么我们又跨过了一个阶梯。

今年的阶梯就是Agent,因为我们发现,用Agent的方式,即便多
有事情也可以做,它的能力范围会更大,它的智能上限会更高。为
什么是阶梯呢?因为后面的每一步都是基于前面的基础上的。
Agent要用到CoT,然后CoT也要用到前面的阶梯,前面的阶梯就是
语言模型,所以它并没有一步是白走的。

所以,AI的发展,智能的走向是有迹可循的。说今年走的这个
阶梯是Agent,但是Agent这个阶梯,它也是会走完的。就是它把所
有可能解决的问题都解决完之后,但是它还是不能替代你的员工,
但是它已经到它能力的上限了。

就好像CoT一样,CoT到它的上限之后,它已经超过最顶尖的人
类了,在做奥数题、写程序上面已经超过最顶尖的人类了。但是它
还是停在那个地方,它那个技术并没有能够到达AGI。所以你看,AI
这个智能的走向,它是有迹可循的。
#+end_quote

认为智能的发展有清晰的脉络，是CoT->Agent.

认为持续学习或者life-long learning很重要。


* 持续学习（AI的自我迭代）与奇点


#+begin_quote
这个奇点就是,当这个模型能够持续学习之后,它已经能够做
人类能做的所有事情了。它就能够自己开发自己的版本,能够自己
再研究,然后开发自己的下一个版本,开发更前的人工智能模型。
所以它就会到一个奇点,能够实现自己的迭代。

但这个奇点,它并不是一个奇点,它也是一个渐进的过程。这
个过程可能也是一个比较长的渐变,它不是个突变。但是习惯性地,
我们都认为它可能是个奇点。

因为在很早之前,那些预言家认为这里会有个奇点,但其实它
不是一个奇点,它是一个连续的过程。然后这一步走完之后,我觉
得才是具身智能。这是我们的推测,这是我们觉得这个时间表应该
是:先解决学习去学习,然后再到那个智能的奇点,能自我迭代的奇
点,然后才是具身智能。
#+end_quote


我还没有完全理解这里的奇点所处的位置。但是似乎具身智能仍然被摆在了这样一种自我迭代之后。

但是无论如何，CoT-> Agent -> 自我迭代 -> 具身智能。 这是Deepseek的总路线图。并且显式强调，没有world model, 视频生成这些。


* 关于权威与共识

#+begin_quote
公司重大战略、技术业务决定的流程和决策机制。我们公司
整体上是建立在共识的基础上的,我并不是说我一个人决定所有事
情,而是我要寻求共识。我在公司内的权威以及在公司内的影响力,
是建立在共识的基础上的。

比如说我要做一个事情,我肯定是先看我们大家的共识是什么,
大家想不想做。然后有可能我会有一些引导或者倾向,但是这引导
的作用是有限的,引导的作用是非常有限的,还是建立在一个共识
的基础上。这个决策机制其实是一种寻求共识的机制,这并不是说
我能够推动一个什么事情,它一定是共识,我才能够推得下去,然后
我才会去推。
#+end_quote


* 克制 v2

#+begin_quote
我不希望我把所有东西都吃了,我只要吃一块就好,我只要吃我最擅长那一块,或者我觉
得我们自己认为最核心那一块,然后跟用户
直接相关那一块,我觉得可能对于我们的很多产业伙伴来讲,
他们比我们更关注类似......应该是别人的意义,不应该我把它诠释
了。未来我们会不会自建大型的集群?我觉得自建大型的集群是
肯定要的,我们自己一直在做这个事情,我们所有的集群都是自己
建的。但是未来要不要自研芯片,我觉得取决于这里的收益有多大,
取决于收益有多大。
#+end_quote


* 组织与工作时间

#+begin_quote
我们公司的管理其实是两条线:一条线是从上到下,一条是从
下到上。从下而上,就是每个人自己想做什么,自己做,没有人管他,
没有KPI。从上到下,就是正式的,我们要集体做一个什么事情,需
要全公司的人一起来配合。

比如说我们要发V4,那么就得分工,每个人得做一部分。那个
是从上到下,然后从上到下这个我们叫做正式。一般我们希望这正
式不要占用员工所有时间的一半,就正式不要超过一半。

他还有一半的时间,是不被安排的,他想做什么就做什么。这
是一个研究的范围,让他可以自己去探索,按照他觉得什么重要,他
去探索什么,没有前置的要求。只要公司能够支持,公司算力能够
支持他做,或者说他不需要算力,他需要做得很少,那么他根本就不
用来协调。
#+end_quote

我觉得我的科研也应该如此。一半时间奉献给我的正常科研路径，一半时间奉献给我想要探索的其他问题。就像Deepseek是一个商业公司有自我存活的需求一样，我认为我的科研也能够满足自我的需求，但是与此同时需要保持足够的克制，把主要精力押注在长期的research上。
