#+title: 跪月集——古诗词相关
#+date: Wed Dec  8 14:44:34 2021
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper
#+filetags: poem:literature:

#+begin_quote
版权要求：遵循CC协议，自由转载但要求署名（BY）、同时禁止演绎（ND）、在非商业使用（NC）的前提下。

转载请加本网页链接：
因为本网页的作品可能会被修改和更新。

姓名： 废石 
#+end_quote

#+begin_quote
声明：以下诗篇均为个人创作，如有雷同，不太可能，但可仿《孟德新书》故事删除。以下诗篇纯粹抒情，绝无暗示、讽刺、批判古今中外现实世界和社会的表达，不含隐喻或其他意图。如有质疑，请联系作者，谢谢。
#+end_quote

** 2021年09月15日

  从兴庆回创新港有感。
  
#+begin_quote
回创新港有感 （日期不详）

四刻来回不堪说，五楼宛转又如何。

广场边上遛鸽子，落地窗前看渭河。

本是共饮同源水，到底成了异乡客。

夜追轻骑人不在，谁人回首盼萧何？
#+end_quote

** 2021年09月15日

  从兴庆回创新港有感。
  
#+begin_quote
回创新港有感 （日期不详）

四刻来回不堪说，五楼宛转又如何。

广场边上遛鸽子，落地窗前看渭河。

本是共饮同源水，到底成了异乡客。

夜追轻骑人不在，谁人回首盼萧何？
#+end_quote

** 2021年09月05日

  与女友两地，因赠此诗。 

#+begin_quote
望江南 秋

蚊声过，暮色爬满东墙。云隐听沁桐叶冷，烟里思寻桂雨香。箫声湿透衣裳。

#+end_quote

** 2021年某月某日

本科同学，于骊山上。  

#+begin_quote

忘记词牌名 与苏乔一起去华清宫

叠云欲渡崖宇，新风几过棋亭。国槐荫下吃豆腐，看天乍雨乍晴。

三年未得相见，两地各自经营。二舍扫楼传单尽，归途里，满天星。

#+end_quote

** 2021年03月28日

  与女友两地，因赠此诗。 

#+begin_quote
七月十五赠W

犹见今年早来春，窗前新绿雨中魂，

如今帘影凋薄暮，屏里容僵尚语存，

长安夜里消长夏，醉景街头忆醉人，

无端坐此工位处，寻书欲笔雨纷纷。
#+end_quote

** 2021年03月28日

   2021年创新港沙尘暴时作。

#+begin_quote

 一上天台满风沙。草地花林，飞虫惨日，漫看几户人家。他在楼台往前眺，他下楼去敲代码，一顿稀里哗啦。

又上天台揽风沙。弥漫，粗犷，任着把愁杀。写完python还不够，再来两行c++，键盘滴滴答答。

今天又是好风沙。乱了呼吸，迷了眼镜，不见眼前花。抬手不得惊退步，蛛网沾衣似华发。低头走过枝丫。

#+end_quote

** 2021年02月26日

   2021年春节，帮叔卖牛肉，于傍晚作。

#+begin_quote

卖肉、干活与来不及汇报

牛肉七斤少，白酒三两三。

就着北风饮，天旋路拐弯。

松木生明火，铁骨熬到软。

头鞭落两地，魂飞魄可散？

千年读汉史，七天懒搬砖。

他趋马走南，我陪狗链栓。

肉多嚼不烂，先把酒言欢。

拾起苍蝇事，夕阳血满山。

#+end_quote

** 2021年01月24日

   无题。2020年冬，创新港玻璃亭。

#+begin_quote

无题

蒙蒙欲。点点血尘，愿随那、烟波去。玻璃亭下听暮雨，了却了，茫茫间几芥心意。

天郁郁，云密密。何处远人歌，调子只随风细。我欲解下千斤雪，它顿化作风和雨。草人无心，答不了，蒙蒙欲。

#+end_quote

** 2020年09月30日

   放假前期作此篇于创新港四号巨构天台。观渭河有感。

#+begin_quote

十六字令三叠 秋

秋，白雾蒙蒙青草旧。西风紧，新寒起未休。

秋，梦入桂园香满袖。懒回顾，不知者何求。

秋，雨过事清倚高楼。月无缺，唯秋水自流。

#+end_quote

** 2020年08月25日

  农历七夕。 

#+begin_quote

江城子.七夕无聊碎笔

清冷银河几光年。鹊成桥，七夕恋。三千灯火，恍恍落窗前。凡人又当求巧艺，夜中紧，白日闲。

一根红线几块钱？教人人，不羡仙，终得相见，桥上有何言。谁忍仰头窥河汉，又逢着，阴雨天。

#+end_quote


** 2020年08月03日

   只觉得人生艰难，夜晚，出门见圆月，有感。

#+begin_quote
六月十四日致月

世事不通空落雨，魂绪如灯火通明。

惶然仰头羞惭见，你我相知多少年。

#+end_quote

** 2020年06月20日

   悼亡。

#+begin_quote
闰四月己心诗两首

其一

树黑疏叶冷，天凉暮色穷。

漫看小园色，寒水不住流。

其二 无韵词

黄土青山热雨浇，西风懒散老萧条。鸟雀飞不过，翱翔到树梢。

愚夫血，痴童笑，壮士头。人间总是无常事，恨饮坡下断头水。少儿应落泪，青丝多少年。

#+end_quote

** 2020年05月25日

   该年未外出求学，于姥姥家，做此篇。

#+begin_quote
燕归巢

某年某月，在姥姥家看到燕巢。当日一大学同学讲一高中同学的故事，有感，作此篇。

燕归巢，燕归巢，巢中哪里有逍遥。念虽在，恨千里，路迢迢。只是心中百事浇，无计可排解，踏遍诗经，寻烂离骚。

燕归巢，燕归巢，巢安在，竟飘摇。朔风黄昏起，星黯淡，雨潇潇。独立寒枝沐新雨，对语春叶解易爻。一谣声奈何。

燕归巢，燕归巢，一任万事劳。百念空，千思虑，到今宵。天涯路远知音少，东走西顾空年少。后来白发人，笑当时的自己啄春泥，筑归巢。

#+end_quote

** 2019年10月18日
大四上学期，离开沈阳时所作。后疫情爆发，终未回沈阳。

#+begin_quote
清平乐 一九年离开沈阳

怨怨怨怨，三年又三年。离别总是清秋日，残月色袅如烟。

长梦未及心事，青山隔路万千。算得相思时刻，年年月月天天。


菩萨蛮 一九年离开沈阳

综合楼上孤观展，大成深处倚栏杆。何须老雪醉，粥尽引人酣。  旧友未别离，便把浑河探。窗外朦胧景，盯着离人看。
#+end_quote

** 2019年09月24日

从沈阳去西安求学，游记其二为当时迷茫时所写。游记其三，去青龙寺散步，有感而作。

#+begin_quote

不知名词牌 游记其二

枕梦初醒时间早，霜晨月亦寒。翻来覆去，昨夜难眠，终究成了云烟。披衣起，帘卷长安，提笔欲字此篇。

无处拾拣，断肠诗句，只得拥衣小憩。天色单薄，衣亦单薄，远上寒烟绿。费劲心思，消磨心事，徒然难逃尘欲！终究是，难逃尘欲，难逃尘欲。


水调歌头 题青龙寺壁(游记其三)

梦里秋光暖，梦醒夕阳堕。乐游原上行人，红尘迷离客。一曲长笛呜咽，几处欢语笙歌，孩童四处躲。秋水明镜里，凡人多快活。

臊子面，鸡排饭，肉夹馍。青龙寺里，过客梁子跪诸佛。纸鸢挂着愁绪，红绳吊着念想，安能学弥勒？不见谁长久，只知痴人多。

#+end_quote
   
   















