#+title:  跪梦集：现代诗选编
#+date: Wed Dec  8 15:56:45 2021
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper
#+filetags: poem::




# * 露霜时期 （2020-2023）

** 五月雷雨

五月二日，打雷。作此篇。
----------

不是一直如此温和

待我

看惯了青苔与花的样子

楠树下吐出的热

在玻璃窗边流过。昨天

炎炎白日，和红霞
----------


应当去寻找激情

还是温情，一个家

从露水的晶莹

到短暂又即将消逝的、焕发着色彩的新生活
----------


走在这条小路，趟着泥泞

终到了五月，滋生出汗水的季节

如同今晚

滚滚夏雷，和暮雨
----------


我于热烈中寻找热烈

发誓绝不在忧郁里落下雨点

明日

煮好鸡蛋，去读论文
----------

**



# * 风雪时期 （2016-2020）

** 思念

------
思念像是一只蝉，爬在B区宿舍的高树上

它在叫啊叫，传到百里之外的这里

当我侧耳

才发现找不到它

------
思念像是一条狗，躺在东南门口看我扫二维码

救护车直来直去，喇叭声不停

它永恒又静谧地张着舌头，在午后不经意闯入我眼前

当我追逐

就看不到它
------

在我思念你的时候

太阳也比从前热烈

叶子比清晨更绿

操场上生成了海市蜃楼
------

还没从午梦中觉醒，便到了这里

从再熟悉不过的往日寻常中转身，像走入四号巨构的走廊

孤自一人担着来回不已的热风
------

可如今，我走入陌生的日子里，撑着你的伞和两侧的梧桐

汗水从头顶滚下

在夏风中颤抖

一步一步爬上楼梯，心里默数着数字

十一，十，九...

2021.8.1

** 感冒

感冒
---------
如果你在昨天晚上出去走一走

即使戴着帽子，裹着口罩

如果你去天台上踌躇

望几眼月亮和灯的光

如果你的耳朵通红，鼻子里的呼吸不是那么流畅
---------

重新来到了这个寒冷的夜晚

没有雪的夜晚

如果你能有勇气从实验室里走出来，去昨天里走走

如果双腿冻得发抖，两脚麻木

开始说一些让身子变暖的话

会让耳朵发红的话

然后迎接无处不在的

温柔刺骨的风

迎接一场感冒
---------

如果你夜晚没有掖好被子

如果你忘记关上窗子

如果你从黑夜里醒来

从旁边的桌台上拿起水杯，小酌一口

或者来不及摸到眼镜，就去洗漱间一趟
---------

外面的天渐渐亮了

你早就发觉时间不早
---------

如果你还在缅怀黑夜

想起那些让人都耳朵发红的话

那些，让身体变暖的话

蓦然坐起

请不要呆住不动

小心感冒
---------

当你像我一样

当你，像我一样无聊

也准备独自出去走走

去天台上踌躇

望几眼月亮，和灯的光

当你想返回那个夜晚

没有雪的夜晚
---------

当你像我一样

被埋在这风雪中，就连呼吸也变得不顺畅
---------

当你像我一样

蓦然坐起，望着天色

就这样走去实验室

当你一半的呼吸被夺走

眼泪掉落下来

太阳穴发胀
---------

请关上窗户，忘记那场温柔刺骨的风吧

不是什么大不了的事，是在感冒。
---------

2021-01-08

** 写给桃子的一首诗

写给桃子的一首诗

（读某校某人的生前书有感，姓名略去化名桃子）
------------

在我得知你的事情时，那晚我身体剧烈地发抖

不是为你而发抖，是为你鄙弃的东西
------------

我从来没有见过你

没有和你聊过天，之前的之前彼此都是陌生人，当然，现在也是陌生人

倘没有你的那点文字那点写得像小说的东西

我到现在都不会记得你吧
------------


哈尔滨的雪下的好大啊

能覆盖所有的疮痍，和不满

我没有你坚强，

我或许也比你坚强

我还是想去经历那些

一生之中必然要去经历的
------------


很久之前

我曾经见过世界上最蓝的天

那时我高高仰着头，对人生是一个俯视

我永远不去想未来将要发生什么

一切事情都很为难，很为难

那时你肯定还不记事吧，桃子

毕竟我也不过是在读幼儿园
------------


再后来嘛，我经历了诸多的美妙

那种感觉就像是

挥动右手中的锤子 狠狠去敲打钢钉

然后砸烂了左边的手指

我的身心满是疮痍

眼角边出现纹路

每次自我审视

都觉得十分好玩
------------


世界称你我为青年

就像是夏天野蛮生长的藤草

像是不停地分泌出杨絮的高大的树

我们直插云霄，还觉得不够高

我们不需要担心自己的容颜，树皮任意被北风吹裂

可惜，树叶上到处都是毛毛虫
------------


还是青年呢

即使树干歪了，叶子上一个个光光的洞

也是青年，也是杨树

即使四处无人，身处沙漠和旷野

也是青年，也是杨树
------------


即使被大水淹没，窒息

也是青年，也是杨树
------------


我不想去关心来生和另一个世界

我不知生，就不去想死
------------


现在你是青年了，永远的青年

木屋，渔船，棺材，你的文字是锯掉的粉末
------------


而我

或将老死，病死，毒死，或和你一样而死

死于战争、车祸、瘟疫和过劳

或将成为一个中年人

我将会像历史上的已存在的那些人那样被后来人嘲讽和蹂躏

然后死而后已
------------


可我还是青年呢，和你一样

现在的我还是一棵杨树  一棵爬满了毛毛虫的孤独的树

就站在你的周围
------------


你曾挺立在哈尔滨无休无止的大雪里

现在我品味着从蒙古西伯利亚一路刮来的又湿又冷的风

任由青苔顺着岁月渐渐爬满我的树皮

把你压垮了的溢出的痛苦，我将一同担着，并愿意带着它过完我的一生

你的对世界的愿望和思索，将和我的放在一起，随身带着，直到那个不是终点的终点到来
------------


桃子，你做出了你的选择，在我认识你之前

现在你选择完了，轮到我选了

------------

十二月八日

** 我讨厌文学

我讨厌文学
----------

像是一个发福又过气的爱豆

在屏幕里兜售假药

我看得热泪盈眶

这时他们分享给我论文，热搜，衣服和菜谱

我分享给他们这则卖假药的广告

"试试吧！很灵的哦。"
----------


把理性和沉思当祭品献给数字，情绪多而不当，就通通叠放这里吧！

那我该用什么生活，或许二者就是我的生活？
----------


在弥天的病毒下戴紧口罩，把钢铁折弯，镜框刚刚可以压上

每一次温热的呼吸，都在我的世界留下一层雾气

朦胧又终将消散的雾气
----------


我在呼吸和雾里生存

文字发霉，又有更多的文字蠕动在我的肠胃
----------


生命就这样划过

在石头里，有如流星
----------


有一天，我会回到那里吧，回到屋里

破洞的沙发，潦草的电视

是一个发福又过气的爱豆

在屏幕里兜售假药

我生命唯一的解药

这药让我爱它，可它从来觉得这不过是假广告

我讨厌文学，还要安利个不停

“试试吧！很灵的哦～”

----------


2021-03-06

** 雨山

雨山 歌词
---------------

那是一个没有情绪的冬天

甚至温度都降不到冰点

我从哪里出发的呢，从何处想到她的呢

淡忘过、便匆匆略过了
---------------


雨下了早就不止一夜

撑着伞便不觉得有雨花抵达在头顶前

这液体让人觉得冰冷吧，让人觉得刻骨吧，让人觉得难忘吧

或许人不该为一场雨而倾心
---------------


裹紧衣服，

温暖里究竟有谁记得谁

北风来去

头发像野草乱飞
---------------


明明天气冻到了极点

为什么还是在零度以上，雪花还是雨滴

它们飘来飘去，你看，这也很美啊
---------------



那是一个没有情绪的雨天

落雪滴滴答答

像昨日的梦飘落在我的窗前

暖气让感情更加冰冷

大梦一场，我穿上衣服，准备起床
---------------


雨下了早就不止一夜

如此彻骨的季节也没有白茫茫的世界

让人失落吗，让人不舍吗，让人错愕吗，

看着纯洁的东西如此融化
---------------


不知道你是否听过，雨水堆积而成的山

就像大雪压倒了孤松

路灯倾泻在无人的公路上

当你收起雨伞

你就能感觉到那种重量

一朵，一滴，一朵，一滴

越湿润，就越干涸
---------------


不知道你有没有见过，雨水堆积而成的山

凝固而不流动

不是致死的冰冷，却一样没有感情

就悄悄地在天地间下着

从上午到中午，再到黑天无人时刻
---------------


我是见过的

在一个没有情绪的冬天，一个雨天

大约我撑着伞

走在它们中间

落雪滴滴答答

大梦一场

我穿上衣服，准备起床
---------------

2020-11-30

** 春


春 
--------

我期待紫叶李开花的样子
​
期待南风来这，从太平洋吹到北冰洋，滋润一切
​
我期待第一声雷隐藏的热情
​
又是羞涩又是大胆
​
那时我一定要在天台上乱走
​
张大嘴巴收集撒下的每一滴泪
--------

我要希望，我要期待
​
让每一个花瓣都能坚强的倒下，像来去无影的风那样
​
把天地间所有的香气闻遍
​
要去找蜜蜂进行生死决斗
​
宿命那样，夺走它们亲爱的
​
只有春天才能品到的甜
--------

等每一种颜色染遍
​
再走到地下，或在早已腐烂破碎的枝叶旁边
​
轻轻告诉它们：这一切都是值得的
--------

可是，该怎么去盼望你呢
​
怎么去应对
​
你的盼望
​
如果不能给你更多
​
比起周围和长夜街上的人流
​
那些带着口罩的陌生人
​
当你把蜡烛一根根吹灭
​
夜色将掩埋山村、道路、城市和学校
​
触目所及
​
这里仅仅是春天罢了
​
——你眼前的春天
​
而有的地方还在下雪
--------

我期待你开心起来
​
把你的气势对准这个世界
​
明早去为每一朵小花都拍一张照吧
​
天气如此之好
​
我听得见大家都在为你祝福
​
自然包括我这样的男人
--------

我期待着你能够获得你所能想象到的美满和幸福
​
来自于你自己、我、以及陌生人的努力
​
我期待你的每一行代码都有意义
​
每一束时光都是值得珍视的
​
等到疲倦涌来，便安然入眠，没有什么值得忧心忡忡
--------

如若人人都能如此就好了
​
该怎么去接受如此澄蓝温暖的天空呢？
​
如若一直行走在广阔冰硬的荒原
--------
​
2022.03.10

** 十一月十一日

--------------
是一种雾。
--------------

是从电视机里流出的灰雪，我用手指把镜片上的灰尘拂去，在图景里留下我的指纹。

--------------
揪出羽绒服缝隙里隐匿的暗淡羽毛，一条，两条，三条。似乎是三个独立的线程，我同时在三节同时上的课上发呆。

汽车薄如蝉翼，我拿着刷子，来来回回，黑夜如漆。墙面凹凸不平，路灯像是那些失真的顶点。

打开蓬头，水流散开，又从耷拉着的躯体流下，模糊不清的温润感开始升腾。感觉渐渐产生了，从外面到了里面，压强溢出到屋子外面，汽水的泡沫一点点挤开。突然有了光。
--------------

“不开灯？”

我看着周围，刺眼，陌生，浮动。
--------------

是一种雾。我想。我走过去。猫发出叫声，它就在门口，伺人开门。牛奶，屏幕，一首歌，新的一天。

2020.11.11
    
** 偷吃灵药的人

偷吃灵药的人 十一月五日
------------

向着太阳出发

奏着巨大的轰鸣乐前进吧！

于云浪之上酣睡

在滚滚棉花糖里行走
------------


黑色秦岭出现得突然

它扯开云雾露出胸膛

清冷寒气围绕四周

一条条山蛇盘满身上……
------------


凡人哦，

若忍不了山蛇的盘绕

何不登上云端独自漂流？

凡人哦，

若在云间会凄然不安

何不学习秦岭，至少脚下还有大地……

------------


坐在这里

总像是走了一遭羽化的老路

层层云雾，很快便不见了人间烟火

如此时间才过得快

一天可以抵得上一年

当时那偷吃灵药的人，是否也会因这许许清流而感冒呢？

------------




11月8日

后记

两首均为来去深圳所做。第二首在飞机上，第一首在等飞机，看见新闻消息有感。

** 黑鸟

-----------

你见过那只鸟吗？

那只黑色的鸟

它常常在西风里沉醉

周身刺满了不详
-----------

黑鸟没有春天，只有此在

和死亡。
-----------

你看见那破乱的鸟毛了吗？

那一地的黑色羽毛

它从来没有飞上过天

一味地舞，舞，舞

扑棱几下，而后直坠

生生不已的死循环

-----------

请不要再引来一阵风了吧

它会跟着旋转

手舞足蹈、漫无目的地挥霍着时间

和感情

-----------

你听过那种沙沙的怪叫吗？

黑鸟不会歌唱

它想表达，却沉浸其中

像孩子一样拍着手，咿咿呀呀 不知所云

-----------

我见过那只黑鸟

我向它投喂一切

亢奋的血，激动的泪，以及星星点点的感情

-----------

你可以看见它，它就在那里

甩着停湿的羽毛，在冰雨里吞咽着寒气

它闭上眼睛，瑟缩着寻找荫蔽，最后埋起了头

-----------

这时

请不要再引来一阵风了。
-----------

2020-04-22

** 宅时

宅时

---------

我独自一人在家，翻来覆去

想着把满天的星光写成诗

今晚没有月亮

那东西过去常常徘徊在我的窗台

深不可测的黑夜里，

这样更加忧伤

---------

我独自一人在家，兜兜转转

想着经营好自己的生活

我用面粉和鸡蛋做出心中的美食

用西江由纪让的音乐洗澡，将晚霞涂抹在身上

我倚着墙壁阅读李白的诗篇

我在窗台幻想，悄悄向外凝望树杈

在无人交谈的日子里

或许这样更加忧伤

---------

那日我独自一人在家，心满意足

我不再担忧或亏欠于谁

我就是我了

再也不用举着镜子端详那个熟悉而不存在的人的脸

外面的云彩聚散

而我就躺在那里

安静地幻想

这样并不忧伤

---------


2020-02-27

** 雪 
雪

---------------

总是不在我在时

下雪

今日早晨

从各个入口，各个虫洞里爬出来的消息

我却躲到了穿短袖的深圳

在立冬由秋入夏
---------------

当我用小竹签吃烧烤

在风扇底下流汗

也会想念满天大雪的景色吗？

或因为身着短袖

才喜欢冷
---------------

今当远离

从夏入冬。从热情的到温柔的

周而复始

回忆才是我的故乡，只缘它是回不去的地方

新闻说辽宁大雪，停课一天

而我却早和它永别了

那个秋天之后，每次暴雪

都想念那个地方……
---------------


2021.11.08

** 狮子狗

狮子狗
--------------

它端坐在桥边，看着我来去

它不会惊讶地张开嘴巴，露出一条长长的舌头

它仍然困着，像是睡醒了的老人
--------------


它不害怕我的石子

也不吠我，似乎知道这是徒劳

它的头上沾了一根麦秆，身上的毛衣蹭满了尘土

就这样目送我来去，似乎早就知道我是个过客了
--------------


它肯定见过像我这样的无数的人

来来去去

甚至要故意停下来，看一看它

然后投一颗石子
--------------


它知道

待那块石子毫无反应

那些家伙都会走了的

投入一只狮子狗，还不如投入一汪死水
--------------


可我不是。

我就要站在这里看着它

桥下的死水虚弱地搏动

暮色渐深，我也不走

我要学这死水看着它

这只狮子狗

直到夜已全深。
--------------


02.17 傍晚

** 迷路的人

-------------
迷路的人啊，你在给谁打电话？

只顾紧蹙着眉眼

你可曾注意过晚霞？

你可曾听见

时间的节奏

滴答，滴答

-------------
迷路的人啊，你是在悔恨吗？

往事顺着下水道流出去

夜色降临，怎么

突然又忧郁啦

只会一首老曲子

再好听的声音也会沙哑
-------------

我想说，今晚我碰见你啦

你早就忘了从哪里出发的吧

路灯和车灯和你的眼睛连在一起

显然，你一个朋友都没有

可是，我却拥有月牙
-------------

迷路的人啊，总之，请这样走下去吧！

十字路口直行

尽头有一个村子

对了

代我吻一下

旁边早已凋谢的紫藤花

-------------

八月二十三日

** 春水
----------

我看见河流，没有波浪的河流，在缓慢地往前走着

我看见哗哗的大雨，夜以继日地下

生锈的闸门开启，任他离开，离开，同意他的放纵

古老的河道边，长满了歪斜的树

在清晨，我看见雾气弥漫

----------

我看见河流的潦缩

像是用尽了力气，吐出尽头的那一点燃烧的灰烬

落叶四布，阴阴惨惨

他渐渐变老，自信不再，越发枯萎

他如此静穆，一言不发

他仍然不甘心地前进,，杀气让云朵远离

----------

我看见他的碧蓝，他的翠绿，他的不透明的白

缩成了小小的一点东西，结成了小小的一长串

他宛如死了，倒在那里

露出几块荒芜的石头，沾着点青苔

他原来也会如此纯洁

如此地抗拒污秽和不雅

可直到他死去，才变得如此纯洁

----------

我看见萧索，灰黑的枝上吐出新的芽

我看见隆隆不止的雷声，躲藏在远方云朵里面

我看见他将到来的热烈，将到来的克制，将到来的衰颓，将到来的死

总有一日，已经过去的和将要来临的

他将缓慢地往前走去，带着无数深埋心底的暗流

没有一丝波浪

----------

在这个清晨，我看见了将来的他

古老的河道边，雾气弥漫

----------

**  阵雨
----------

我经历过他一日又一日的烤灼

----------

我也曾期待他的转变，期待得如此着急，却又过于着急

我的着急从未让他离开

或许他早晚会离开

----------

此刻的空气不同于别刻的气

其中弥漫着香烟的色

我的呼吸不畅

焦虑就这样懒惰起来

我曾以为我愿意为他付出全部

可我仍然无法享受他

我四处闪躲，无处闪躲

他的焦躁是如此的灼人，像是溺在混浊的思索里，夺掉我的呼吸

----------

我总会对他倾注情感

他倏然而来，像是一阵摇摇晃晃的风

就像是某个方向的加速度猝临又突然停止，他变了，然后离开了我

来时我觉得愕然，去了又让我不舍

----------

那是某一年的七月或者八月

一如同今天这样的太阳，云彩，和欢声笑语

我见证了他的降临和离开

正如此刻我之经历

所有的内心独白，碎碎碎的情绪如同一场无因无果的阵雨

把我浇醒、灌醉

----------

我怀念那场短暂的阵雨

艰难的日子，反倒成为生命中最值得回味的时刻

----------

2020-07
