#+title: 《中国崛起不可承受之错》之我鉴
#+author: 梁子，软件学院，3120305385
#+date: <2021-05-31 周一>
#+latex_class: elegantpaper
* 重题中国之崛起
有关中国崛起之措辞，盖出于北京奥运之后。百年前，满清有广志，自称“天朝”，一场八国联军，究竟威严扫地；方志敏《可爱的中国》，愿景为“屹立世界民族之林”，此后半世纪革命风烟，只求不为亡国奴而已。
待新中国成立，前抗美援朝，后击越打印，士气虽强盛，语境中更有单薄之处也。后改革春至，瞻仰西方世界，无所不学，以东洋西洋为首之风，至今未绝，四十又二年矣。
当零七年时，众人眼中中国之国力，尚不敢与日本相乘，如今十四年弹指过，局势竟成中美之对抗，何其速也！
有人慨：中国之崛起，不可谓不迅也。然察古：满清自傲为天朝，倏然而落，不过二十载；国人自信日增，老人尚存敬畏，孩童便目中无人，此之观B站言论可知也！

故崛起一词，不可不慎，自二零一二年至今又是九年光阴，以此小十年观中国之变化，时局并非乐观。
今借郑永年《中国崛起不可承受之错》一书，以此九年为验证，不妨书生妄语，作继往开来之新谈。

* 自二零一二至二零二一：崛起否？有错否？
  
** 郑公意见总结
 郑公论“不可承受之错”，单指“颠覆性错误”尔。其所列内政十篇，外交十篇，洋洋洒洒，到底是宏观、激昂、冷静的文字。愚浅分之为四类：
 1. 论制度。首以王权、相权为鉴，谈论党权和行政权的协调；之后，但看政府，述反腐的负面，大胆而合理；单观党权，以权力交接担忧为稳，更是委婉而一语中的。今回首，某些问题已经浮出水面，前途不知。
 2. 论政经。政经者，安家立民之本。所述意识形态、财产分配等事，皆是极要紧又极难解决的事。此等要事，无他，试尔。成则名垂青史，败则身败名裂，甚至国运不在。然不试，终究滑向灭亡的深渊罢了。
 3. 论动乱。动乱可怖，作者之担忧，怕步文革之后尘也。
 4. 论战争。中日之争、中印之争、南海之争、阿拉伯世界、台湾解放、香港失控、颜色革命，作者列此七条。此七条中，中印摩擦不断，香港出而后平，以印证其预测也，所幸该隐时隐，雷厉得乎分寸，以是局势暂时稳定。

 观此四条，我有观点如下：

** 中国已崛起，然未完全崛起
   有关崛起，此处略去闲言，成就数不胜数，崛起毋庸置疑。此番崛起，全赖邓公改革开放之功，三十年之积累，才成今日之中国，后续如此几年，不过显露出来罢了。
   然，观华夏之古巨，大汉孝武、孝宣之烈功，唐宋中心之繁荣，此日之中国，道阻且长。由此可见，当中国收复台湾、琉球，收服日本、朝鲜、中南、蒙古、中亚，力压印度、欧陆、美陆，
   方算得上真正之“崛起”。这绝不会是辽远的将来，但未必会是很近的将来。台湾收复，当为一标志节点，有西汉得西域、北宋得幽州之效。

** 患寡还是患不均
   平等是中国两千年的核心。西汉以此得繁荣，失于王莽政，东汉多豪强，以是不长久。毛泽东搞土地革命，竟有推翻三座大山之力。国外，英伦圈地运动，沙俄叶卡捷琳娜二世改革，均埋葬了农业，
   成就工业化之时代。今之印度，土地问题尚无解决，不可不哀也。

   工业时代以降，吃饭不难，难于生活。此时资本家之于打工人，正如地主之于佃农。一国繁荣与否，不在地主精英，全在打工人之处境。打工人有钱，则消费繁荣；打工人安居，则人口发展；打工人不劳苦，则文艺兴盛。打工人没钱，则消费降级；打工人不得安居，则怨声载道，政权不稳；打工人劳苦过度，则文艺暗淡。今观房价、生育、996、老龄化、躺平等诸多矛盾，不过此一矛盾耳。依愚之间，此矛盾是中国崛起与否之最大挑战。过去九年，此矛盾越加激化，后续或更激化。
  
** 民主与专制
   民主虽然，然专制为此时代更需之物。郑永年拒绝X之LR，非理智举。俄之普京，德之默克尔，均连任数届。俄罗斯新立时寡头横走，普京岂无功哉？德意志新国之成就，默克尔又无功否？倘流水做皇帝，英、法、美之成就当真可称？

   以笔者之见，中国需要一个连任的主席，这样才能收复台湾、与日本交战、抗拒美国和印度，完成一带一路和最重要的关乎中国命运的、解决平等问题的社会改革。这个主席坐二十年，三十年，都可以，只要别坐一辈子，如果后期会有这种结果，我梁子愿意第一个维护宪法。但此在的二十年，一个连续的政策和集体，是必须的。
   
* 自二零二一至二零四九：我眼中中国社会之未来

** 台湾问题非战争不可收复，中日问题非战争不可解决，中美之间不需要战争
前言论：收复台湾将是中国崛起之重要节点，那么如何收复？当今舆论，武统意见已成主流，早非郑永年所谈论，以此可见，战争不可避免，战争之难，无人可预见，然不打则不能收复，不收复，则无东亚南亚霸主地位。不王东亚南亚，则无崛起之谈，遑论中亚西亚崛起于世界也。然此时，中日或有一战也。日本，东亚大国，自视承中华正统、续西方绝学，中国抗战虽胜，日本仍不认同，此非战争不可解决。中美则不需要战争，中美之间，文明之冲突也，地远义偏，故可商议，可代打，凡此种种。
** 扶贫重要，但扶打工人更重要
现实已证明，人人平等的计划经济不可取。若计划经济不可取，当如何解决当下的平等问题？
当下政府做扶贫，效温铁军言做乡村振兴，自然是社会主义国家必要的事，但更重要的，是为当下的年轻人找到出路。这条路难度更高，危险更大，但不得不做。只有为年轻人解决住房问题，工业化方能继续。如若不然，北方除却北京一无是处，南方三大集群之外同样颗粒无收。工业非农业，不赖农田、全赖产业，而产业之布局，又赖国家也。资本能拘之乎？

** 中国社会的三种结局
窃观中国未来，大抵三种结局：

1. 结局一： 中国成为世界第一，城乡繁荣不尽，科技、军事领先，住房、教育、医疗均有保证，人人有所养，怡然自得。此景需外交无敌于欧美，内政善修以巨头。当一国统领材料、能源、信息三者为己所用，以智能化待有志之人，消解巨头，成新基建，则万事可期。此时，诸国来朝，修礼以建构新国际秩序；继承左志，无论黑人、白人、红人，悬壶广济天下苍生，此之谓新中华之崛起也。
2. 结局二： 中国综合国力跃居世界第一，然无力管理世界，中、美、德、日、印、英、土耳其、俄罗斯、伊朗形成九国联盟，建立新联合国。国内，贫富分化，资产阶级形成新家族企业，私人教育林立。四大城市圈房价居高不下，社会重新稳定，城乡流动停滞。工人细化为赤贫工人、懒散温饱工人、较富裕工人和富裕体面工人。赤贫工人、富裕工人、资产阶级成为生育主力，较富裕工人和富裕工人被认为是中产阶级，数目逐渐减小，以扩大赤贫工人和懒散温饱工人的比例。国家机器越来越难通过税收从资产阶级中获得收益，小资产阶级、无产者成为税收主力，由此使得整个国家机器越来越难以维持。
3. 结局三： 中国爆发革命，难以预料结局。


个人认为，结局一是最好的，但难以实现，如果力度不够，就会滑向结局二——结局二是悲哀但又最可能会产生的结局。如果力度太大，不排除结局三。但结局三的可能性总是小的，结局二是最悲惨又最真实的结局。
