#+title: 被掩埋的巨人-阅读杂感
#+author:liangzid 
#+FILETAGS: 读书笔记 
#+date: Fri Sep 10 11:38:45 2021
#+email: 2273067585@qq.com 

被掩埋的巨人一书，大意是一对老年夫妻，为了找寻记忆中的儿子而踏上旅程的故事。而书中实际出现巨人一词，不过是是在夫妇旅行中，遇到了一个巨人的坟。其后，由于在村庄的经历，夫妻两人多了一伴侣——一位武士和一个小男孩。再之后，他们又遇到了年迈的老骑士。整本书若只读开头，或许会被误认为是现实生活题材，仅仅是迷雾和失却记忆，令人有一丝丝的魔幻现实味道。可随着剧情铺展开来，整本书的剧情性就被打开了。食人兽、恶龙、精灵、巫师……一大堆元素将整本书装点的十分有趣。而里面大量的隐喻也在试图拉深该书的深刻性。

隐喻，终于谈到点子上了。这本书的隐喻是相当多的，其中最明显的，也被探讨更多的，是关于种族之间的仇恨。不列颠人和撒克逊人之间的斗争，应当以什么结局结束？书中给出了三种视角：
1. 男主视角：通过法律保证彼此权益，双方和谐共处；
2. 高文骑士：忘却。忘却仇恨，就可以消解仇恨。
3. 武士：征服和杀戮。

从历史的角度来看，武士的道路是最终的结果。历史上，应格鲁撒克逊人入侵不列颠土地，最终不列颠人基本灭绝消失了。但这并不代表武士所说的是对的，按照加缪的观点，真理打不过武器，但是真理加上武器比假道理加上武器更厉害。而真理，可以看作是正义，正义，就是道义。从道义上来看，男主视角是伟大的，伟大未必会被历史选择。至于高文骑士所作的事情，有人将之同“忘却历史意味着背叛”挂钩，我不这么认为。亚瑟王的意图，很显然是一种省事的做法，而省事的做法，最大的问题就是不够深刻，最终导致不省事。这也是为什么这种措施最终会烟消云散。

还有很多人将该书的民族问题引申到中日问题上，我不赞同。中日问题的性质和文中的民族对抗大不相同。中日问题，是以民族集体为基础的侵略，是硬生生的战争。中国境内没有几个日本人，日本军队打进来，就是为了征服、掠夺和欺压，就是为了损害他人，便宜自己，和德国法西斯没有区别。而书中的对抗，同英国土地上的历史也有不同，书中的对抗是建立在已有土地民族群落的基础上的，拿之讨论当代欧洲的原始种族与迁移种族之间的关系稍稍更为恰当。

我倾向于将本书当作故事书看，而非纯文学形式的其他书籍。这本书的剧情是比较精彩的，且书中大多数过渡不着痕迹，除去高文的浮想等意识流部分或山羊的插叙之外，全书的描写十分正常，不去追求花哨的写法，这正是深厚根底的表现。这本的剧情，如果非要列举一些相似的作家，我还是觉得村上春树可以入选。但如此的剧情，一个问题便是不具有广泛性。因而，这本书实在不适合套用到什么种族关系上。

和这个话题相比，我更喜欢的是，反而是文中夫妇的感情。互相扶持，互相关爱，安慰、顺遂，一直到老到死，这样的场景，无论何人看了，都会心生感动吧。不管年轻时有多少的仓促的爱恋，不管过去有多大的伤痕，竟然平静的日子，一天一天，也可以将这些东西都消泯，最后留下一种平静的感动。这便是我期待的爱情啊。看到他们的老年，才能理解当下的我，我的当下，不过是一瞬间的悲欢离合，便更加有耐心走完后面的路了。