#+title: 读恩格斯《家庭、私有制与国家的起源》有感
#+date: Thu Mar 30 17:09:32 2023
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper


#+begin_src 
今日摸鱼成果记录。  
#+end_src

恩格斯通过一个摩尔根这个美国人对文明出现之前的原始部落的研究——也就是对当时美洲所存在的印第安人的研究，补充了在西方文明背景下希腊罗马之前的历史空白，从而构建起了对“家庭”、“私有制”、“国家”三者起源的思考。

本文将首先对其核心思路进行总结，随后补充中国的证据。
* 家、私有制、国三者的起源
** 对家庭与国家的一般性印象
略。

** 人类早期文明的简单划分

摩尔根简单将人类的文明划分为三个部分：蒙昧时代、野蛮时代、以及文明时代。下面是一些标志性事件：
+ 蒙昧时代：
  + 早期：以果实坚果等为食，住在树上
  + 中期：鱼。火。石器
  + 晚期：弓箭、房屋。
+ 野蛮时代：
  + 早期：粘土，制陶
  + 中期：畜牧，农业
  + 冶铁
+ 文明时代：国家形成，私有制产生，阶级产生


由此可以发现：
1. 现在的一些生存类游戏基本上是基于上述流程构建的，但是，为了保证游戏的乐趣，一般的生存类游戏不会进入到最后的文明时代。
2. 从蒙昧时代到野蛮时代，更多的是生产力提升而带来的“量变”，便没有引起生产关系的巨大变动，但是从野蛮时代过渡到文明时代时，虽然没有其他的科技上的革新性的变化，但是由于 =生产力已经能够使得财富产生剩余= ， 所以产品可以被遗传（私有制）和交换（变成了商品），人类的文明形态由此因为经济结构而发生了巨大的变革。


下面是恩格斯对上述时代的三个总结，我认为这个总结一般：
1. 蒙昧时代的特点：获取天然产品
2. 野蛮时代~：制作辅助工具
3. 文明时代~：畜牧、农业。财富可积攒（我加的）

然后，如果我们把上述的三个时代——这些西方社科研究人员的结果放到中国历史上去考察，我们会获得后续2.1章节的思考结果。

让我们把视角移回西方。一般认为，氏族（这里用了氏，旨在代指以女性为纽带的血缘关系集合）是文明时代前的产物，而文明时代石器则变成了父权的家长制。这是为什么呢？为什么母系部落会瓦解呢？——因为私有制的产生。为什么国家会代替血缘组合呢？——是由于商品交换而带来的分工的产生，使得新的利益集团得以确立。

所有的这些后续都会进行介绍，但是此处应当首先对家庭进行简单的剖析。

** 家庭制度的流变
家庭制度——当前的主流的家庭制度是一夫一妻制。但是，在恩格斯的眼中，实际的当前的家庭制度是：“一夫一妻+女性出轨+男性花钱买淫”制。上述名词是我自己制作的，可能会产生误解：比如为什么出轨要强调女性？比如为什么女性就不能买淫等等。这些问题后面会解释。主要的是：恩在写该书时的核心目的是，首先批斥当时流行的所谓从动物开始人类一直都是一夫一妻的观点，其次分析家庭中男女双方究竟是一种什么样的关系，最后再去讨论这种关系的未来。

首先，不妨根据摩尔根等人的调研总结人类婚姻制度的流变：

+ 群婚
+ 对偶婚姻
+ 专偶婚姻


所谓的群婚其实就是乱性，即接触婚姻的成本为零（甚至本身就是接触的），繁衍可以在同血缘和不同的代际之间进行。群婚在一开始的百无禁忌，完全可以通过希腊神话等古老的故事反映出来。由于这种混乱的繁衍，所以一个人要找到父亲，——是困难的。但是要找到母亲，却很简单。这也就导致了原始社会多是母系社会，也就是前面提及的氏族。在中国，通过姓和氏对母系和父系进行了区分，后来母系的划分衰弱，这导致氏逐渐被姓所取代。

那么，这种群婚制度是怎么进化的呢？初步的人伦是如何产生的呢？书中认为是自然选择的结果。即由于自然选择，那些偏好于乱伦的，所生出的后代在竞争力上会天然地弱于那些严格执行了某些婚姻规范的。这个观点在学过进化论的学生里应该是很显然的。也就是这个原因，普遍地，群婚中有两条约束：1）不允许和跨代的亲属通婚；2）不允许和同代的近亲和远亲通婚。这两条约束成为了绝大多数部落的规范，但是，与此带来的问题就是——由于母系氏族中的人都是具有血缘关系的，那么应当如何去构建这种群婚制度呢？

经过考证，大概原始部落的组织结构是这样的：每个氏族都会有一些经常交流的关系比较好的氏族，如果我们给他们起个名字，可以叫胞族。所谓的通婚便是，氏族的女性获取其他氏族的男性，构成婚姻。生的儿女里，儿子们作为劳动力再“嫁”到其他氏族里。注意：这里不存在说氏族A的某个女人和某个男人结婚这一说，因为所有的女人都享有这个男人，而同样的，这个男人也享有所有的女人。换而言之，群婚更多的是集体与集体之间的交配（在澳大利亚的土著中，甚至显著地有这两个集体），是生而就有的、婚姻。

在这样的一个基础上，对偶婚姻出现了。所谓的对偶婚姻，其实就是占据主导地位的女性，选择长期和某个男性待在一起。换而言之，这个女性放弃了和其他男性进行性行为的权力。这是因为什么？恩格斯认为（如果我没有理解错的话）这是因为爱情，这和后面的专偶婚姻有很大区别。值得指出，在这时，对偶婚姻是那种很脆弱的婚姻，或许人一变心，婚姻就解除了。——这让我想到了现在的男女恋爱，大概就是这种脆弱程度。

上述便是对群婚和对偶婚姻的简短介绍，于是马上，重点就来了，——专偶婚姻——父系社会——私有制——家庭，这四个东西几乎一体地登上了历史舞台。


为什么，在这种很不错的母系社会下，会产生父系社会的变动呢？对近亲结婚的两条约束明明已经解决了人类生理上进化的问题呀！答案是：因为生产力的发展。

具体地，随着畜牧业和农业的发展，人类靠大自然吃饭的依赖程度进一步减弱，很快，人类发现只需要很少的劳动时间就可以获得较大的食物，从而人类的财富出现了剩余。比如畜牧业，不像打猎，羊群自己就可以繁衍啊。那么问题来了，这些自己用不到的财富，人们会怎么做？人们产生了至今仍在做的两件事：
1. 同他人做交换，来获得其他人所拥有的东西。
2. 传给后代。

   
在这场变革之中，由于男性是生产资料（生产工具）的所有者，也是负责获取食物的人，所以男性获得了集中的财富，而女性所从事的家庭劳动虽然很有意义，但是，由于不具有这种资产的可积累性，男性渐渐占据了更加重要的地位，而当男性要把这些工具传给后代时，他就希望能够传给的是“自己的后代”，由此，父系社会便渐渐产生了。

同时，在这种过渡中，由于古代很难判断一个孩子是哪个男人的，所以掌握了这些财富的男性便构建起了一种特殊的独裁——即专偶制。这种制度把女孩养在了深宫内院，以确保孩子是自己的。而在这种制度下的家庭中，可以发现，男性和女性分别扮演了剥削者和被剥削者的角色。为什么这么说？因为女性无法创造出能够用于商品交换的价值，而男性可以。所以，在专偶制度下，可以发现女性毫无地位可言，社会不会教育他们，也不会让他们从事生产和劳动。恩格斯的有一段话说得很清楚，摘抄之：

#+begin_quote
可见，个体婚制在历史上决不是作为男女之间的和好而出现的，更不是作为这种和好的最高形式而出现的。恰好相反。它是作为女性被男性奴役，作为整个史前时代所未有的两性冲突的宣告而出现的。在马克思和我于1846年合写的一个旧的、未发表的手稿中，我发现了如下一句话：“最初的分工是男女之间为了生育子女而发生的分工。”43现在我可以补充几句：在历史上出现的最初的阶级对立，是同个体婚制下的夫妻间的对抗的发展同时发生的，而最初的阶级压迫是同男性对女性的压迫同时发生的。个体婚制是一个伟大的历史的进步，但同时它同奴隶制和私有制一起，却开辟了一个一直继续到今天的时代，在这个时代中，任何进步同时也是相对的退步，因为在这种进步中一些人的幸福和发展是通过另一些人的痛苦和受压抑而实现的。个体婚制是文明社会的细胞形态，根据这种形态，我们就可以研究文明社会内部充分发展着的对立和矛盾的本质。
#+end_quote

那么这个制度带来了什么？一夫一妻，就是爱情吗？当然不是！因为这种一夫一妻，完全就是基于“经济层面”的考量。这个制度所带来的，除了时代的合理性之外，是其他的东西：

1. 由于男性掌握财富，所以男性成为了买淫的主体。所以男性首先就对他的妻子不忠了。这种不忠，在财富和生产资料较多的那些男性里表现尤甚；
2. 由于女性被强制要求忠贞，所以“绿帽子”成为了已婚男性的噩梦，也成为了女性的自我放逐的反抗方式之一。例如《甄嬛传》和西方的骑士偷情文学。
3. 在上述两条的基础上，爱情大概率是反抗这种专偶制度的结果。
4. 专偶制度成为了一种特殊的买淫。区别于妓女按次收费，专偶制度直接就是，花钱买去一生的忠贞。一个形象化的理解，可以是彩礼。
5. 于是，所谓的道德，无论是孔子式的，还是基督式的，说白了都是：“在文法上双重否定代表肯定，在婚姻上两个卖淫便是美德。”
6. 对于那些大家族式的管理方式，整体的家长不再是一家之父，而是一个大家族的某位家长，这时就会不可避免地出现《红楼梦》里的扒灰现象和《白鹿原》中的丑闻。

进入资产阶级时代，专偶制度的主要问题没有发生根本的变化。唯一变化的是，由于主要生产资料由土地、劳动力变成了机器和知识劳动力，所以家族式的组织形式逐渐解体，而家庭以最小的单位存活。此时，家长们的发言权降低，所谓的“自由恋爱”开始出现。但是，值得注意的是，这种自由恋爱是虚无的、虚伪的。当女性仍然需要承担家务劳动、减少社会劳动时，这就导致婚姻仍然是一种“一生买淫”活动。这就导致：在婚姻里，财富情况会超过个人的好恶而成为第一抉择标准，这一点在那些经济困难、无产阶级与资产阶级矛盾尖锐的岁月里尤是。


可幸的是，1949年以来，中国的女性一直在社会劳动中占据着重要地位，这使得中国的女性一直比其他国家更加拥有女权。而这，还是建立在中国1840年仍然是一个传统的封建社会的基础上，可见中国的女权之优势。

当这一点足够成熟时，可以预见：“：这一代男子一生中将永远不会用金钱或其他社会权力手段去买得妇女的献身；而这一代妇女除了真正的爱情以外，也永远不会再出于其他某种考虑而委身于男子，或者由于担心经济后果而拒绝委身于她所爱的男子。这样的人们一经出现，对于今日人们认为他们应该做的一切，他们都将不去理会，他们自己将做出他们自己的实践，并且造成他们的据此来衡量的关于各人实践的社会舆论——如此而已。”

** 从氏族到国家(state)

那么，氏族社会又是怎么瓦解，让位于另一种组织形式——国家的呢？

还是私有制。当然，这里的国家还是西方意义上的国家。根据恩格斯对雅典国家的形成，他所得出的结论是：由于私有制和商品交换的发展，形成了阶级。阶级形成后，依据阶级而形成的利益集团比传统的的氏族社会更加有利于进行统治压迫，所以就形成了国家。

这个理论很不错，虽然能够解释地中海区域的雅典的情况，但是却不足以解释中国的情况。在国家形成的早起，一般会有一些胞族所形成的讨论性质的联合体。当这种联合体足够抽象且势力足够大时，国家便形成了。

未完待续。。。



* 笔者的思考

** 当前的婚姻制度发展到了何种阶段？

** 中国古代文字可记录的时期具体处于什么时期？

** 从原始社会形态对比儒家的崇古思想和马恩著作中的崇古思想


