#+title: 对《十七地论》中“菩萨地”理念的分析
#+date: Tue Jun  6 21:35:30 2023
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper
#+filetags: ::


唯识家以为，世间万法——一切存在的事物，都有三自性，也都有三无性。三自性是遍计所执性，依他起性，圆成实性；而三无性是相无性，生无性，胜义无性。

原来唯识学立论，以为宇宙万法，皆是能变的心识、所变起之境，这即是‘万法唯识’。而心识所变的外境，依其原始的性质，可分做三类：

一、妄有性： 这类事物本来没有本体，是我人假立名相而有的，而我人却普遍的执著计较，计较的物件，不外是名称言说或义理，名称言说不是实有，只有‘妄有]。

二、假有性： 这类事物，是因缘和合——众多因素条件所生起的，如以砖瓦木石筑成房屋，以泥土工具做成瓶钵，它没有本身的实体、自性，不过是‘组合’的存在 (仗因托缘的生起存在) ，这也不是实有 ，只是‘假有’罢了。

三、实有性： 这是诸法的实体、自性，它不是虚妄的、暂时的存在，而是绝待的、超越的存在，事实上这是诸法绝待的理体，也即是‘实性’——真实的存在。

以上三类，在佛学术语上称为‘三自性’——即是遍计所执性，依他起性，圆成实性。如 <解深密经> 上说 ：‘云何诸法遍计所执相，谓一切法，假名安立，自性差别，乃至为令随起言说； 云何诸法依他起相，谓一切法缘生自相、、、、、、云何诸法圆成实相，谓一切法平等真如。’经文中的‘相’字，在此处就是性的意思。所以，换一个方式说，三自性就是：

一、遍计所执性： 这是我人对一切事物，普遍的执著计较。执著于五蕴和合的假我为实我，执著于条件组合的假有为实法。或执于相，或执于名，或执于义理，时时计较，处处计较，这一切执著计较，就是我人烦恼生起的原因。

 

二、依他起性： 依他起的‘他’，指的众缘——众多的因素条件。世间万有，没有孤立生起或存在的，全是因素条件的组合。既是组合，就会随著组合条件的改变而变化。所以它没有‘自性’ ——即是没有固定不变之性。

三、圆成实性： 圆者圆满，成是成就，实是真实，合而言之，就是圆满成就的真实体性。这真实体性不是事相，而是‘理性’——超越相对的绝待真理。也就是二空——在我空和法空之后，所体证的理体。这理体也就是真如。

三自性，是以依他起性为中心。仗因托缘生起的事物，只是暂时的现象，不是永恒的实体。我人若在这因缘和合的事物上执著计较，这就是遍计所执性——普遍的计较执著，执我执法、执常执断。如果彻悟诸法缘生，常一切时，在依他起诸法上、无遍计所执的实我实法，这就是圆成实性。 <唯识三十颂> 上说 ：‘依他起自性，分别缘所生，圆成实于彼，常远离前性。]  前性，指的是于依他起法上，远离普遍执著计较的遍计所执性。



一切诸法，各具三自性，同时也各具三无性，那就是相无性，生无性，胜义无性。无性，就是无自性。试想，宇宙万有，无非全是一时组合的假相，依此假相，而立假名。我人在这一切假名、幻相上执著计较，假名幻相何尝有其自性？ 其次说生无性，依他起之法，是仗因托而生起的，它是随著因缘的聚散而生灭，它何尝有固定不变的自性？ 最后是胜义无性，所谓胜义，就是真如。 <唯识三十颂> 曰：‘此诸法胜义，亦即是真如，常如其性故，即唯识实性。’唯识实性就是圆成实性。圆成实性是超言绝虑的绝待之法，显二空之妙理，所以说胜义无性——胜义如果有自性，就不是绝待的胜义了。


中道：非空非有。

                                ┌情有——非空
                    ┌遍计所执性┤
                    │          └理无——非有
                    │
                    │          ┌假有——非空
      三性各具中道—┼ 依他起性 ┤
                    │          └实无——非有
                    │
                    │          ┌真实——非空
                    └ 圆成实性 ┤
                                └无相——非有
