#+title: Rethinking the Methodology of Handling EXAMS : a Case Study and Conclusion from IELTs
#+date: Sat Sep 16 19:21:43 2023
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper


NOTE: this tutorial can help you to handle a specific type of exams, on which you might want to obtain a expected SCORE which will influence the futre significantly, if you have a terrible results. I summerize three points for you to handle an exam easily, which can be seen as follows:

** SWITCH MODE: you cannot prepare an exam without pressure, planning, and time

I believe there exists two types of "life mode"  for most of the people, like "work mode" with less pressure but the concentration of works, "relax mode" just do nothing, and so on. If you need to prepare an exam which is important for you and you know you even will not learn that after the exam, then I think you should switch to a specific new mode for this exam. That is to say, you'd better force yourself on it during a quite narrow periods, and try your best to battle for the expected results -- you will not do it again in future. *You can see from this describtion that you are not favour in this exam, the prepartion procedure is boring, and even painful.* What you need to do is, find a best solution, a methodology, to pass it, to fulfill the requirements of the exam score, in a given priod of your lifetime. I called what you do in this periods as a new "MODE".

*** Reference of this methodology

根据《阮一峰的网络日志》中对纳瓦尔的引用，纳瓦尔对赚钱提出了三条建议：
1. The most important and determinuted factor of success is not working hard, it is a serious decision of selecting your work, your staff (collabrators), and your project.
2. The most effective work methodology, is not like marathon which focusing on preserverance, but a burst when you need a burst, and other times stay healthy and great.
3. You must be like a lion, leaping into action at the sight of opportunity,instead of a cow, working from dawn to night.


*** Definite the MODE for your EXAM

**** SELECT the RIGHT KPI

+ TIME we pay on
  + We should set a netherworld, a  threshold you must learn every day at least
  + But you cannot define your target from time, because time is not linearly relative to the score. It will cause "low-efficiency".
+ Score of simulations
  + Yes, you need that. If you can achieve 130\% at least of score of your expected finally score, then, you are OK for exam.


**** REORGANIZE all your activity to THINGS related to this EXAM

You need to transform all your hobbies and others in this periods, to the things related to your exam.
Take IELTS as an example, you should:
1. read English books if you like read books.
2. watch English TV or movies if you like watch videos.
3. listen to English music if you like to listen to music.
4. Writting in English if you need to write something.
5. Replace the self-speaking in your heart into English if you...
6. and so on.

   
   You can take 30 minutes to swtich all of your apps, and materials to that.


** SIMULATION or PRACTICE: in REAL-WAR

*** Set a deadline.

NOT up to one month.

If you set a deadline, just do it. Don't say: I am not prepared. You will never be well-prepared. Just do it, receive the result that you failed, and do it again.

*** Simulation

**** Collect materials.

in 60 minutes.

**** Practice methodology

***** Knowing the basic types of the exam

+ how much questions in your exam?
+ summerize the types of the questions
+ in these questions you are afraid of
+ the discrepancy between your expected score and now your score


***** Improve by repitition which is not a repitition

Based on the bilibili video of "我不是肥宅", I summerize some of the key points to improve IELTS scores:
1. At first, we should focused on give a "correct" result without time limitation. For instance, we can listen to the materials time by time until we make sure we have all tracked the correct answer of the questions. Finally, we can check the results to see if we have a idea score of what we want.
2. Regard ourselves as a neural network with a low but stable learning rate, and consider this simulation is the training data. The reward is the score we obttained.


NOTE that: *You must make progress everyday, where the progress is what you can see obviously by your own eyes, not something like "Oh today I have spent three pure hours on  that and it is Okay". NO, you must do that, you must earn the reward for your attemptions today. In any way, you must get the progress, even a quite tiny one. This is the keypoint for your improvements.**


***** Let the bullet run, and waiting.











