#+title: 多方安全计算原理与相关库介绍
#+OPTIONS: html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/worg.css" />
#+date: Fri Feb  3 14:31:38 2023
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper


* 多方安全计算相关

** byteorder

用途：以大端或小端的方式对二进制数字进行编码和解码。

** bit-vec

用途：现在看来和素数相关，未详。

ref：https://contain-rs.github.io/bit-vec/bit_vec/

** num-traits

用途：为通用数学中所存在的traits所构建的collection

** ndarray

用途：rust中的numpy

** rayon

用途：并行计算库

** blake2

用途：hash function blake2的封装

** rand_chacha
使用chacha算法的随机数生成器

** npy, npy-derive
用以读取和写入numpy库所用到的npy文件。
** tch
C++ pytorch库的rust绑定
** ocelot
不经意传输的rust实现
** scuttlebutt
多方安全计算相关的基础library
** bincode
对变量进行编码和解码
** io-utils
network wrappers
* 通用
** derivative

derivative是常用的依赖，他可以自动化地为一些自定义的enum或struct提供一些标准的trait，如构造函数Defualt，用于复制的Copy和Clone，等等。

参考连接：https://mcarton.github.io/rust-derivative/latest/index.html

** clippy

用途：代码规范。

ref：https://github.com/rust-lang/rust-clippy

** failure

用途：错误处理库




** colored
用途：colored outputs

** criterion

用途：评估代码块，代码测速

** std::io

io opearation of rust. It provides two tratis: Read and Write.

** macro_rules!
create macro for rust.

** #[inline]

an =inline= features, which suggests the compiler inline this function.

** std::io::Cursor

the buffer of memory in rust.

see: https://doc.rust-lang.org/std/io/struct.Cursor.html

** std::marker::PhantomData

幽灵数据，Phantomdata<T>是一个范型变量，表示类型为T的变量可能存在

** bindgen
为C或C++生成rust bings
** cmake
通过使用cmake来为rust构建C++的native labrary
** crossbeam
并法编程相关




