#+title: 对佛教中“声闻地”理念的批判分析与解读
#+date: Thu May 18 21:04:49 2023
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper
#+filetags: ::

近日将毕业，无事，故理三年来所观群书，有《存在与时间》《通鉴》《瑜伽师地论》未读完。此处剖十七地论，单拎“声闻地”之修行与哲理解析之。
* 修习“声闻地”
** 綱要

当以“四聖諦”（苦、集、滅、道）爲綱，以得“阿羅漢果”爲目標。欲修聲聞，當以“行”爲極重，以下爲法則：

1. 理解“苦”：觀察事物之 =無常= ， 所受皆 =苦= ， 理解 =空= ， 了解“無我” 。
2. 理解“集”： 因 集 起 緣
3. 理解“滅”： 滅 靜 妙 離
4. 理解“道”： 道 如 行 出
** 對 “苦” 的理解與觀想
當理解：

1. 一切有情世間皆是“無常”。此處的無常是指事物會發生變化，不存在永恆。即事物會變異、滅壞、別離等等。
2. 一切器世間皆是無常。地球有一天也會毀滅。注意：此處的無常不是沒有規律的意思，而是不會永恆不變的意思。
3. 由有情無常，當知有生老病死、愛別離、怨憎會、求不得等相；
4. 由器物無常，當知有成壞住空等相；
5. 由因緣交會，當知人的行爲有“不自在”相，即人在江湖，身不由己。

上述1，2，3，4可總結爲“諸行無常”（不如稱爲“易”）。

藉助這種變化，可知人之所受，皆是眼、耳等諸色根以及內心思緒等無色根所產生的結果，而由於其無常，所以“人之 *所受皆苦*，也皆樂。”

由於人的行爲的不自在相，當知其行爲大多數時候並不是“真我”的想法，而是由心念隨波逐流的“雜念”，或由於社會與外界壓力（即因緣）而導致的不得不做，因此，當領悟 *逐行無我* 。

總結一下，世間萬物都有4種特點中的至少一種，即：
1. 無常：器世
2. 苦：有情世間
3. 空：無所得
4. 無我：不自在

爲斷滅此苦，當了解與觀察“苦”的產生過程，即苦的因緣，此爲“集”。下文解之。
** 對“集”、“滅”、“道”的理解與修行
知苦後，即可以四相觀苦之來由，即苦何所因，何所集，何所起，何所緣：
1. 以愛而因。（？存疑）
2. 因集而集。（？） 了一解：耽於苦，一葉障目，思緒專注之，故名之爲集
3. 因接續而起。了一解：苦可接續不斷，耽之，爲苦。
4. 以種子攝受爲緣。了一解：種子有二解：1. 人之生理特性，如飢渴困；2.習慣。

修習聲聞，當觀察內心之苦道來由，直到無師自通。

認同世界之無常、苦、空、無我之後，可謂知苦。觀察理解熟練苦以愛爲因、以種子攝受爲緣、因集而集、因接續而起後，可謂知集。由此可觀苦之本諦爲滅：

1. 苦非實體，因此
   1. 永遠熄滅，是爲滅相
   2. 永遠寂靜，是爲靜相
2. 這種靜態超然與世界之上，故爲”第一義“，是爲妙相
3. 這種靜態是永恆不變的，不依附與世界，曰出離，是爲離相。

至此，當解苦因其靜理而現滅、靜兩相，永出離不動，是第一妙義。

（道諦待補充。）
** 對四聖諦的總結

苦諦，在於察覺並認同苦，由此從無到有，確立分析對象爲”苦“。

集諦，對苦的因緣變化進行分析，由此得到苦是怎麼來的，怎麼沒的，等等。

滅諦，對苦進行現象學分析，給出了苦的現象分析，即滅字，由此說明其廣泛存在道特性。

道諦，XXXX
* 声闻地的其他问题

修習聲聞，當除”我慢“。所謂”我慢“者，我知而尓不知，唯獨我知，是爲我慢。所謂自大自傲者也。

若有我慢，則心向往涅磐，故”四聖諦”反成執念，此執念則生愛，僥倖得之，則有樂受，若不察覺，則心無法證入“滅苦”之道，由此苦集滅道反倒未修成，由此共虧一潰。故《金剛經》談“誤作是念”，即關不能以果爲慢也。

* 對四諦的批判与思考
待補充。




