#+title: 为什么我无法再也提笔写出一篇小说了？
#+OPTIONS: html-style:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/worg.css" />
#+date: Mon Feb 21 14:36:29 2022
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper
#+filetags: literature:thinking:


今日动手打算撰写一篇新的小说，此时才发现我已经有足够长的时间没有再去写一篇小说了。此次断层的时间长达半年，这是一个让我较难回答的问题。我梳理了一下，距我上次所写完的最后一篇作品《城门卫兵》写完已经过去了将近一年的时间，而距离我最后未完成的《凶宅》也产生了大概3个月的时间。

此文记录了我的内心变化以及对此事的反思。
*** 三观的固化
我认为，让我第一次产生转变的原因来自于我三观的变动。记忆中我是一个邪恶且善于伪装的人，可幸我从小学开始学习了一些忠恕宽仁的道理。因此我小时候的一些十分亲近的玩伴可能还残留有一些我恶魔一般行径的印象，而我父母只不过一直以为我很乖罢了。也是因为如此，直到现在我一直对未入学甚至刚入学的小孩静而远之。可惜进入初中后由于我发育较慢，只知道宽容忍让，竟然成为了别人欺负的对象。如此我方理解自然界的弱肉强食，我不肯认同于野蛮的威力，却又自我束缚于礼义廉耻之中，这让我对过去的人生观产生了怀疑。待我进入高中后，我便又换了一个人，虽然不再像儿时那么奸诈，但却更加滑头。那时的我谎话连篇、利己不已，甚至生怕再掉回初中里。后面我去东北上大学，反思高中认为做事太阳太刚，但前两年并没有什么提升。

在我大三时，或许是追逐功利到达了极限（我这里的功利并不是绩点等东西，而是个人的一种无限制的野心），我的身体终于出现了报警。我终于从走马观花的境界里深入了一点，并借助焦虑等神经上的痛苦开始了我新的人生思考。在此之前，我曾经狂热地追逐过各种广泛存在于目前社会的主义。就是在这样一个我身体似乎毫无问题、但内心却觉得旦夕将死的背景下，我产生了我的人生观、世界观，以及价值观。

我那时自觉失去了时间，可是却成了10多年求学路来最闲适的一段日子。我那时自以为一切都要结束了，所以才，所以才看到了一些终极的问题吧。

总之，从那时起，我找到了拯救我焦虑、恐惧的解药，我开始为一生做打算，而非一时。这是一条无比积极、无比光明、无比险恶的道路。从这时起，文学的一些意义，在我这里就……不再是意义了。









*** 身体的影响

    由于过去心理压力产生的阴影，我怕我再写小说会对我的身体产生负面影响。因为写一篇小说，要动无数次情。撰写小说前后的波动感，是一种无与伦比的体验。

