#+title: 《瑜伽师地论》（《十七地论》）本地分枝络小结
#+date: Fri Jun 16 09:45:17 2023
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper


电子书资源见维基书库，但是我又发现好像这个版本更好，目录更清晰：http://buddhism.lib.ntu.edu.tw/BDLM/sutra/chi_pdf/sutra14/T30n1579.pdf

或许后面还会重读一遍。



笔者曾两次阅读《瑜伽师地论》，第一次阅读是在上海，仅到十七地的“意地”便停止了。原因无他，繁杂琐碎而已。后来研三无事，爬慈恩寺、涉雁塔，方重新动念阅读此论。未料此番阅读如此通畅，故于此记录之。

* 本地分

所谓“地论”者，主要论“地”也。何为地？或谓“修行境界”，然何以有“六识”？所谓“地”者，当译为“支流”、“组件”、“现象类别”等类。此地略有四类：


** 解法相。

对“我”面前诸法相（现象）的剖析与总结。此包括面向色界诸色相的“五识身相应地”与包含无色界诸余蕴的“意地”。由于意地统摄受想行识，心法繁杂，故为重点。余切在分析诸地时，侧重观其本性如何，所依如何，所缘如何，助伴者何，可作何业等等。

** 解方法。

对佛所说止观之法作解，论修行禅定的七地：有寻有伺、无寻唯伺、无寻无伺、三摩四多、非三摩四多、有心、无心。其思路为：先观自身，知苦海浮沉，而后寻伺清净、解脱、真如，以消烦恼、所知二障，此之为“有寻有伺”。当内心以清净为本能，故无需寻，唯伺此清净、解脱、真如自至，所谓“无寻唯伺”尔。然清净乃本来清净，解脱乃自解脱，所谓本来无一物，故最后当舍掉“伺”之心，方为真清净、真自在，故有“无寻无伺”之解。综上，可得如何修三摩四多，此为三摩四多。知何为三摩四多，故可知何非为三摩四多。有心无心者，乃总结前述五地（五识、意、寻伺是否有）也，除无寻无伺地中的无想定、无想生、灭尽定外，其余皆是有心地。笔者附：当知此三类三摩四多禅定境界仍为法，其中诸番善、恶、无记性质仍为法、法相，故此论仍侧重于为此诸多法相作解、作分别，可于此学法、修法、证法，然当知此说法所为为体察，而非指导手册也。

** 解何以得方法。

对佛所说何以得三摩四多之支流作解，论得道的三地：以闻而得，以觉（或曰，悟）而得，以修而得。以此书脉络，或许声闻乘偏于闻，独觉乘偏于觉，菩萨乘偏于修。然当知声闻亦有修，菩萨亦有闻觉也。

**  解成佛法门与修行境界以对应何以得此方法。

对佛所说法之流派作解，论到达彼岸的三种途径：声闻、独觉、菩萨。所谓声闻，当知此法可解烦恼，破我执，修之以观苦、集、灭、道四圣谛为主，即能通过器世的“成坏住空”与有情世间的“生老病死爱别离怨憎会求不得”以及“缘起缘灭”所起的“不自在”相了知“无常”，能通过观自我的五蕴体会到无我与空，由此察觉到苦的存在。而后，细致地分析苦，以体察苦的诸相，即以爱为因、因集而集、由接续而起、以种子摄受为缘，由此了知“何为集”。基于苦与集，则可灭此苦，证清净，得所谓的“道“。所谓独觉，独觉之义也，此处略。《十七地论》一书，主要解菩萨地。其所述又十分繁琐复杂，此处仅以笔者之解作此拆解，以示脉络。略述菩萨地之诸法相，功包括种姓、发心、自利利他、真实义、威力、成熟（诸漏尽）、菩提（得智慧）、初持瑜伽之种姓、施、戒、忍、精进、静虑、慧、摄事、供养亲近无量、菩提、功德、随法瑜伽之菩萨相、分、增上意乐、住、究竟瑜伽之生、摄受、地、行、建立等种种。由此可知，静态地，菩萨当有根器，发心，了如来之真实义，最终成熟、得菩提。如何修呢？即瑜伽。也就是，初持、随法、究竟。初持者，如佛所说诸等行，最终可得菩提。随法，未细看，略。究竟，未细看，略。此处单解何为”真实义“。真实义者有四种：对器世无常的真实理解、对道理的真实理解（不懂）、对人生诸烦恼的真实理解和破除、以及对法我真谛的真实理解。所谓器世的真实理解，当知所谓世间为妄有、假有、缘有、无相实有。所谓道理真实义，没理解。所谓烦恼障解，当知四圣谛，且能以止观之法解之。所谓面向所知障的真实义，则是在”无我“之上破解恶取空了知诸法非空非有（所谓中观），即”于一切法离言自性假说自性平等平等无分别“。

**  解彼岸
即涅槃，以论寂灭果。有二：有余依与无余依。若证阿罗汉果，可灭除“后边依“外所有依。何为后边依？不知。


以上五类即为《十七地论》本地分脉络，总结一下即为：法相二、禅定相关七、所成法三、所成法对应乘三、有无所依二，共计十七。

