#+title: 《周易》与算卦
#+OPTIONS: html-style:nil
#+date: Fri May 20 17:18:55 2022
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper

前两天一友因找（互联网）实习的问题而倍感焦虑，我常言安慰也无法开导他。最后我给他说，不妨用《周易》算一卦，结果他竟然真的信了，于是我给了他一卦，说是地雷复。然后劝他：“你之前的一次面试后状态就差一次，信心就少一次，实习机会就丢一次，内心越来越焦虑，做的活却越来越少。所以现在一个实习也没找到。现在实习阶段已经结束了，可以理解为剥到头了。如果后面慢慢回过劲了，秋招还是很有希望的。当然，那时候就需要考验人的耐心了。”我这一卦算的并不高明，因为我只是随口而说了一卦，然后自己解释了一下。这位友人内心中其实本无斗志，全是沮丧，哪里当着起一个雷震之德呢？我只是用以安慰他罢了。毕竟： *人总是相信玄学，而不相信自己日积月累的努力* 。

同样地，认识一个学妹，之前和别人谈恋爱不到一学期就被要求分手了。她后来喜欢上一个新的人，也是我身边的同学，但是那位同学不太情愿。这段感情可以说渐渐快落下去了。今日闲谈时，她像我倾诉这件事，我也假装给她算卦，说了“风天小畜”。大意是：她是风，那个目标是天，风为天而畜。其实就是应的卦辞“密云不雨”。我说下不下雨对她而言是结果和目的，这不是她可以决定的，但是收集云彩，形成密云，——这一点是她可以去做的。至于形成密云之后会不会在这篇天空里落下雨滴，并不比形成密云本身更重要。我不知道她听懂了多少，但我想通过这种方式或许可以缓解这种所谓的“爱情焦虑”吧。

而其实上面两个例子我都没有真正用什么术数的方式去算什么卦，我不过是自己先有了一个观点，然后假托卦辞。而我自然也不相信算卦的各种方法。这里的核心问题是：周易到底是什么？

在我看来，《周易》可以看做是一种抽象的符号模型，可以理解成是一个pattern。0与1是最简单也最普遍的两种pattern，8卦是八种高度概括的pattern，文王和春秋战国、秦汉的诸儒将封建社会以及集权社会下的百态凝练成64种pattern，而在每一个具体的分支里，细节上的pattern有384个，对应384爻。这些卦是有优劣的吗？当然！乾卦之德可谓是最普遍、最受用无穷的，而后面的诸卦常常受限于各种场景。

对于这样的一个环绕于主人公的世界，每次都检索出相似的模型然后套用，这自然是一种不错的生活方式，这也必然导致《周易》并不是仅仅是单纯的预言而是一种行动论上的指南。所以在这里：从来也绝对不会存在任何的宿命论。宿命论是什么？宿命论是把结局放在首位，一切为了目的和成果并无限拉低行动的重要性，而所有的儒家理论都把结局放在了次要的地位上。所以周易的语言实际上是一个“如果-那么”：当你的行为和状态贴合了某个“象”那么就很有可能获得那个象上的结果。

那么，为了追逐人生的智慧，我去读这本书，可以吗？这我显然是不推荐的！理由有三：1. 天底下的道没有一个是通过说理学到的。如果一个人看了某句话就信奉为真，那么这种人还配读书吗？真正的读书与其说是把知识填在脑子里，不如更像是：把心中有这类感觉但还未抽象、熟悉、凝练的思想进行打磨和确认。最接近道的方式是走近这个世界啊——傍晚的阳光、身边人的谈话、如此种种……观察和领悟越多，书就读的越透。读了《周易》，看这个世界会觉得什么都顺眼：天、地、风、山，等等等等。2. 检索+模型匹配是一种取巧的做法，但并不是一种大而化之的做法。放在神经网络模型上看，检索式总是寻求已有的最切近的描述，而真正美妙的却应是生成那些不存在的描述。前者需要大量的信息冗余，而后者则是融会贯通之后的一个精简版本。周易天然地是一种纯粹以象说理的哲学学问，这便不得不要求每个人得拿自己的人生去体悟，这也是为何周易里史事宗可以出现。就像中国广阔的在家天下背景下的历史，当你真正熟读之后，你不应说“我现在的情况和某代某人遇到某事时一样”，而应该忘记那些历史——直接学到应该怎么去做。3. 追逐人生的智慧是一个伪命题，因为大家不需要智慧，大家需要的是别人觉得自己很智慧之后产生的一系列感觉。

发觉以上三点，可以解释明明是一种活的、用于世的学问，为啥社会面上“精通”周易的人，多是三种：踏踏实实做学术的、给普通人和大老板卖课的所谓“大家”、以及广泛的算卦分子。应该去问：为什么科学家们不用？创业者不用？工人不用？农民不用？文艺工作者不用？公务员不用？他们所解决的事情是用不到这个吗？还是：他们已经变相掌握了这些东西呢？还是：他们不仅掌握了这些东西，还愿意天天受用，天天精进，不过没有用这些称呼去解释呢？

我强烈安利以下人读《周易》，如朱熹的《周易正义》：1. 喜欢读《诗经》和《古诗十九首》的人。因为周易好多地方写的太美了，哈哈哈;2. 喜欢读《四书》的人，因为二者的哲学思维实在是十分接近;3. 喜欢折腾的人。

