#+title: 《资本论》笔记
#+OPTIONS: html-style:nil
#+date: Mon Mar 21 19:04:03 2022
#+author: Zi Liang
#+email: liangzid@stu.xjtu.edu.cn
#+latex_class: elegantpaper
#+filetags: reading:note:

今日由于疫情窝在宿舍，经过多日的堕落之后，终于打算找点新的乐子。之前约定和同学一起读莎士比亚戏剧，现在读到莎士比亚的历史剧，觉得毫无乐趣可言。尤其是《亨利四世》，这群人对皇帝的家事为什么这么感兴趣，简直比《资治通鉴》中两晋时期的变乱还要无聊。看见kindle里有一本资本论，便决定拿出来闲时读读，以调调胃口。

我此前从未读过资本论的全文，也没有系统地阅读过别人对这一领域嚼过一遍的甘蔗。按照老马本人在法文版出版的序言里所写的话，这本书似乎是先难后易。希望如此吧！

* 笔记1： 商品、劳动、与货币
  马克思研究的对象是资本主义社会，该社会的经济特征我理解为：万物皆可商品化，即尽量将一切东西都变得可以买卖。如此以来，资本主义社会中的每一个人——都日常生活都在从事于劳动，且这些人永远都在不停地购买商品。如果我们把这样的社会视作一个有机体，那么处在这个有机体中最重要的细胞级别的对象，便是商品和劳动者。于是马克思借助于商品先进行微观的分析。但值得注意的是，对商品的微观分析，仍然是建立在社会的宏观交换之上的，这一点在后面有所体现。

  马克思发现了商品的两个最重要的属性：1. 风格各异的使用价值和2. 所有商品均统一的“价值”（交换价值）。在商品经济社会之前，每个物品同样有其使用价值，但因为不进行社会交换而缺失交换价值。因而，对于自给自足的小农社会，小明的姥姥为小明纳了一双鞋底，这个物品虽然有使用价值，却无交换过程，因此没有价值。从这个角度上讲，是频繁的交易滋生了价值的传播。
而即使是在商品经济社会下，也有很多有使用价值无价值的物品，比如人人都需要的空气。

  那么，如何衡量商品的使用价值和价值？马克思认为，除去原材料的特质，商品的使用价值来自于人类的加工。而商品的交换价值，则来自于人类为创造该产品付出了多少心血。为了去掉不同水平的人类劳动产生的波动，寻求一个最普遍的规律，马克思给了“社会必要劳动时间”来描述某个社会的某个时刻平均人类的劳动心血付出。如果学习过概率论便知道，这个概念相当于我们先构造一个多元概率分布，这个概率分布的多维输入用以反映人的多种特质属性，而概率的结果则是心血程度，在这样的概率分布下，社会必要劳动时间指该概率分布的数学期望。我们可以发现估测这个数学期望是困难的，更何况这个值会因分布的变化而变化。这或许就会导出不同经济体制的优劣。

  如此一来，商品依照其用途展示出两种价值：使用时的使用价值和交换用的交换价值。而劳动而因为商品展现出两种劳动：千差万别的、性质不同的、无法比较的、具体的的劳动，以及统一的、单纯的劳动。前者正好对应了使用价值，后者对应了价值。理解劳动的第二个特征，使得交换成为了可能。

举个例子，一块肥皂，50年前生成可能需要的社会必要劳动时间是40，而由于社会生产力的发展，现在生产1块肥皂只需要4，那么这块肥皂的价值，约等于缩减了10倍。而这块相同的肥皂，其使用价值或许没有变化，甚至还变大了，但是其价值，便会如此的缩水。那些过去被视作昂贵的、如今由于各种原因而变得便宜的商品，都包含着价值降低这样的一个事实。

 说起来，正是由于商品交换，才产生了使用价值一说。而价值的过程，按照马克思的分析，则是如此的一种抽象表达：x个A产品值y个B产品，这表示A的交换价值可以用B的使用价值来进行担保。倘若在此基础上，B可以一般化地为所有的商品都进行这种担保，那么，B也就成为了货币。由此可知：1. 货币本质上是一种商品。这就意味着，如果限定不同的“小岛”，那么货币其实可以有很多。人们只是采用货币作为一种等价交换罢了。  





